src/objects/MT_AdvertisedMediaProduct__c.object
<CustomObject>
    <description>Produkte, die von externen Partnern oder Assets in Media Transparency beworben werden.</description>
    <label>Advertised Media Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertised Media Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaMotive__c.object
<CustomObject>
    <description>Definiert ein Werbe-Motiv, das im TV ausgestrahlt werden kann. Die Datensätze werden über die Flightplanung gepflegt.</description>
    <fields>
        <fullName>MT_AdvertisedMediaProduct_ref__c</fullName>
        <description>Das Produkt, das mit dem Motiv beworben wird.</description>
        <label>Advertised Media Product</label>
        <referenceTo>MT_AdvertisedMediaProduct__c</referenceTo>
        <relationshipLabel>Media Motives</relationshipLabel>
        <relationshipName>MT_MediaMotives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_AgencyProductNumber__c</fullName>
        <description>Die Produktionsnummer der Agentur.</description>
        <label>Agency Product Number</label>
        <type>TextArea</type>
    </fields>
    <label>Media Motive</label>
    <nameField>
        <label>Media Motive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Motives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaMotiveService_Test.cls
/************************************************************************************************************
Name:  		MT_MediaMotiveService_Test
======================================================
Purpose: 	Test class for MT_MediaMotives, MT_MediaMotiveService and MT_MediaMotiveSelector
======================================================
History
-------
Date		AUTHOR						DETAIL
15.03.2017	Falco Aulitzky             Initial architecture & development
*************************************************************************************************************/

@isTest
private class MT_MediaMotiveService_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_MediaMotives amp = new MT_MediaMotives(new List<MT_MediaMotive__c>());
    Test.stopTest();
  }

  testmethod static void getMediaMotivesByIds() {
    MT_AdvertisedMediaProduct__c amp = [SELECT Id FROM MT_AdvertisedMediaProduct__c limit 1];
    System.assertNotEquals(null, amp);

    MT_MediaMotive__c mm = [SELECT Id FROM MT_MediaMotive__c limit 1];
    System.assertNotEquals(null, mm);

    Test.startTest();

    System.assert(!MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>{
      mm.Id
    }).isEmpty());
    System.assert(MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>()).isEmpty());
    System.assertEquals(amp.Id, MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>{
      mm.Id
    }).get(0).MT_AdvertisedMediaProduct_ref__c);
    System.assertEquals('Test Motive', MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>{
      mm.Id
    }).get(0).Name);

    Test.stopTest();
  }

  testmethod static void getMediaMotivesByIdsWithFields() {
    MT_AdvertisedMediaProduct__c amp = [SELECT Id FROM MT_AdvertisedMediaProduct__c limit 1];
    System.assertNotEquals(null, amp);

    MT_MediaMotive__c mm = [SELECT Id FROM MT_MediaMotive__c limit 1];
    System.assertNotEquals(null, mm);

    Test.startTest();

    System.assert(!MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>{
      mm.Id
    }, new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).isEmpty());
    System.assert(MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>(), new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).isEmpty());
    System.assertEquals(amp.Id, MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>{
      mm.Id
    }, new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).get(0).MT_AdvertisedMediaProduct_ref__c);
    System.assertEquals('Test Motive', MT_MediaMotiveService.getMediaMotivesByIds(new Set<Id>{
      mm.Id
    }, new Set<String>{
      'Name'
    }).get(0).Name);

    Test.stopTest();
  }

  testmethod static void getMediaMotivesByAdvertisedMediaProductIds() {
    MT_AdvertisedMediaProduct__c amp = [SELECT Id FROM MT_AdvertisedMediaProduct__c limit 1];
    System.assertNotEquals(null, amp);

    MT_MediaMotive__c mm = [SELECT Id FROM MT_MediaMotive__c limit 1];
    System.assertNotEquals(null, mm);

    Test.startTest();

    System.assert(!MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>{
      amp.Id
    }).isEmpty());
    System.assert(MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>()).isEmpty());
    System.assertEquals(amp.Id, MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>{
      amp.Id
    }).get(0).MT_AdvertisedMediaProduct_ref__c);
    System.assertEquals('Test Motive', MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>{
      amp.Id
    }).get(0).Name);

    Test.stopTest();
  }

  testmethod static void getMediaMotivesByAdvertisedMediaProductIdsWithFields() {
    MT_AdvertisedMediaProduct__c amp = [SELECT Id FROM MT_AdvertisedMediaProduct__c limit 1];
    System.assertNotEquals(null, amp);

    MT_MediaMotive__c mm = [SELECT Id FROM MT_MediaMotive__c limit 1];
    System.assertNotEquals(null, mm);

    Test.startTest();

    System.assert(!MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>{
      amp.Id
    }, new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).isEmpty());
    System.assert(MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>(), new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).isEmpty());
    System.assertEquals(amp.Id, MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>{
      amp.Id
    }, new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).get(0).MT_AdvertisedMediaProduct_ref__c);
    System.assertEquals('Test Motive', MT_MediaMotiveService.getMediaMotivesByAdvertisedMediaProductIds(new Set<Id>{
      amp.Id
    }, new Set<String>{
      'Name'
    }).get(0).Name);

    Test.stopTest();
  }

  testmethod static void getMediaMotivesByAgencyProductNumbers() {
    MT_AdvertisedMediaProduct__c amp = [SELECT Id FROM MT_AdvertisedMediaProduct__c limit 1];
    System.assertNotEquals(null, amp);

    MT_MediaMotive__c mm = [SELECT Id FROM MT_MediaMotive__c limit 1];
    System.assertNotEquals(null, mm);

    Test.startTest();

    System.assert(!MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>{
      '12345'
    }).isEmpty());
    System.assert(MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>()).isEmpty());
    System.assertEquals(amp.Id, MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>{
      '12345'
    }).get(0).MT_AdvertisedMediaProduct_ref__c);
    System.assertEquals('12345', MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>{
      '12345'
    }).get(0).MT_AgencyProductNumber__c);

    Test.stopTest();
  }

  testmethod static void getMediaMotivesByAgencyProductNumbersWithFields() {
    MT_AdvertisedMediaProduct__c amp = [SELECT Id FROM MT_AdvertisedMediaProduct__c limit 1];
    System.assertNotEquals(null, amp);

    MT_MediaMotive__c mm = [SELECT Id FROM MT_MediaMotive__c limit 1];
    System.assertNotEquals(null, mm);

    Test.startTest();

    System.assert(!MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>{
      '12345'
    }, new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).isEmpty());
    System.assert(MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>(), new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).isEmpty());
    System.assertEquals(amp.Id, MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>{
      '12345'
    }, new Set<String>{
      'MT_AdvertisedMediaProduct_ref__c'
    }).get(0).MT_AdvertisedMediaProduct_ref__c);
    System.assertEquals('12345', MT_MediaMotiveService.getMediaMotivesByAgencyProductNumbers(new Set<String>{
      '12345'
    }, new Set<String>{
      'MT_AgencyProductNumber__c'
    }).get(0).MT_AgencyProductNumber__c);

    Test.stopTest();
  }

}