src/objects/MT_AdvertisedMediaProduct__c.object
<CustomObject>
    <description>Produkte, die von externen Partnern oder Assets in Media Transparency beworben werden.</description>
    <label>Advertised Media Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertised Media Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaMotive__c.object
<CustomObject>
    <description>Definiert ein Werbe-Motiv, das im TV ausgestrahlt werden kann. Die Datensätze werden über die Flightplanung gepflegt.</description>
    <fields>
        <fullName>MT_AdvertisedMediaProduct_ref__c</fullName>
        <description>Das Produkt, das mit dem Motiv beworben wird.</description>
        <label>Advertised Media Product</label>
        <referenceTo>MT_AdvertisedMediaProduct__c</referenceTo>
        <relationshipLabel>Media Motives</relationshipLabel>
        <relationshipName>MT_MediaMotives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Motive</label>
    <nameField>
        <label>Media Motive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Motives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaMotives.cls
/************************************************************************************************************
Name:  		MT_MediaMotives
======================================================
Purpose: 	Domain class for MT_MediaMotive__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
17.02.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaMotives {
  private List<MT_MediaMotive__c> scope;

  public MT_MediaMotives(List<MT_MediaMotive__c> scope) {
    this.scope = scope;
  }

  public static MT_MediaMotive__c create(MT_AdvertisedMediaProduct__c product, String name) {
    return new MT_MediaMotive__c(
      MT_AdvertisedMediaProduct_ref__c = product.Id,
      Name = name);
  }

  public class MT_MediaMotivesException extends Exception {
  }
}