src/objects/MT_AdvertisedMediaProduct__c.object
<CustomObject>
    <description>Produkte, die von externen Partnern oder Assets in Media Transparency beworben werden.</description>
    <fields>
        <fullName>MT_Account_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Der Account, dem das Produkt zugeordnet ist. Alle Produkte eines Accounts (Opportunity -&gt; Account) stehen für dessen Kampagnen zur Verfügung.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advertised Media Products</relationshipLabel>
        <relationshipName>AdvertisedMediaProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_ProductNumber__c</fullName>
        <description>Die Produktnummer, die im Motivablagesystem verwendet wird.</description>
        <label>Product Number</label>
        <type>TextArea</type>
    </fields>
    <label>Advertised Media Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertised Media Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_AdvertisedMediaProducts.cls
/************************************************************************************************************
Name:  		MT_AdvertisedMediaProducts
======================================================
Purpose: 	Domain class for MT_AdvertisedMediaProduct__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
16.02.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_AdvertisedMediaProducts {
  private List<MT_AdvertisedMediaProduct__c> scope;

  public MT_AdvertisedMediaProducts(List<MT_AdvertisedMediaProduct__c> scope) {
    this.scope = scope;
  }

  public static MT_AdvertisedMediaProduct__c create(Account acc, String name, String productNumber) {
    return new MT_AdvertisedMediaProduct__c(
      MT_Account_ref__c = acc.id,
      Name = name,
      MT_ProductNumber__c = productNumber);
  }

  public class MT_AdvertisedMediaProductsException extends Exception {
  }
}