src/objects/MT_AdvertisedMediaProduct__c.object
<CustomObject>
    <description>Produkte, die von externen Partnern oder Assets in Media Transparency beworben werden.</description>
    <fields>
        <fullName>MT_Account_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Der Account, dem das Produkt zugeordnet ist. Alle Produkte eines Accounts (Opportunity -&gt; Account) stehen für dessen Kampagnen zur Verfügung.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advertised Media Products</relationshipLabel>
        <relationshipName>AdvertisedMediaProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_ProductNumber__c</fullName>
        <description>Die Produktnummer, die im Motivablagesystem verwendet wird.</description>
        <label>Product Number</label>
        <type>TextArea</type>
    </fields>
    <label>Advertised Media Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertised Media Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaFlightMotiveAllocation__c.object
<CustomObject>
    <description>Speichert die Zuordnung eines Motivs zu einem Flight und enthält zusätzliche, buchungsrelevante Informationen zur Ausstrahlung.</description>
    <fields>
        <fullName>MT_MediaProduct_ref__c</fullName>
        <description>Das Produkt, dass in dieser Zuordnung gebucht wird. Kann von dem Master des Motivs abweichen (z.B. bei allgemeinen Remindern, die im Paket mit einem spezifischen Produkt verwendet werden).</description>
        <label>Advertised Media Product</label>
        <referenceTo>MT_AdvertisedMediaProduct__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>Media_Flight_Motive_Allocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Flight Motive Allocation</label>
    <nameField>
        <displayFormat>MFMA-{00000}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Flight Motive Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaMotive__c.object
<CustomObject>
    <description>Definiert ein Werbe-Motiv, das im TV ausgestrahlt werden kann. Die Datensätze werden über die Flightplanung gepflegt.</description>
    <fields>
        <fullName>MT_AdvertisedMediaProduct_ref__c</fullName>
        <description>Das Produkt, das mit dem Motiv beworben wird.</description>
        <label>Advertised Media Product</label>
        <referenceTo>MT_AdvertisedMediaProduct__c</referenceTo>
        <relationshipLabel>Media Motives</relationshipLabel>
        <relationshipName>MT_MediaMotives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Motive</label>
    <nameField>
        <label>Media Motive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Motives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_AdvertisedMediaProductSelector.cls
/************************************************************************************************************
Name:  		MT_AdvertisedMediaProductSelector
======================================================
Purpose: 	Selector class for MT_AdvertisedMediaProduct__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
06.02.2017	Duc Nguyen Tien             Initial architecture & development
16.02.2017	Falco Aulitzky				Updated architecture
*************************************************************************************************************/
public with sharing class MT_AdvertisedMediaProductSelector extends MT_Selector {
  public static final String objectAPIName = MT_AdvertisedMediaProduct__c.SobjectType.getDescribe().getName();

  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty())
      return new List<SObject>();

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where Id in ' + constructInClauseString(recordIds);
    system.debug(query);
    return Database.query(query);
  }

  public List<SObject> getRecordsByAccountIds(Set<Id> accountIds, Set<String> fields) {
    if (accountIds.isEmpty())
      return new List<SObject>();

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_Account_ref__c in ' + constructInClauseString(accountIds);
    system.debug(query);
    return Database.query(query);
  }

  public List<SObject> getRecordsByProductNumbers(Set<String> productNumbers, Set<String> fields) {
    if (productNumbers.isEmpty())
      return new List<SObject>();

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_ProductNumber__c in ' + constructInClauseString(productNumbers);
    system.debug(query);
    return Database.query(query);
  }

  public List<SObject> getRecordsWithMotivesByAccountIds(Set<Id> accountIds, Set<String> mediaProductFields, Set<String> motiveFields) {
    if (accountIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(mediaProductFields) + ', ( SELECT ' + constructFieldString(motiveFields) + ' FROM MT_MediaMotives__r) FROM ' + objectAPIName + ' where MT_Account_ref__c in ' + constructInClauseString(accountIds);
    system.debug(query);
    return Database.query(query);
  }

  public List<SObject> getRecordsWithFlightMotiveAllocationByAccountIds(Set<Id> accountIds, Set<String> mediaProductFields, Set<String> flightMotiveFields) {
    if (accountIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(mediaProductFields) + ', ( SELECT ' + constructFieldString(flightMotiveFields) + ' FROM Media_Flight_Motive_Allocations__r) FROM ' + objectAPIName + ' where MT_Account_ref__c in ' + constructInClauseString(accountIds);
    system.debug(query);
    return Database.query(query);
  }
}