src/objects/MT_AdvertisedMediaProduct__c.object
<CustomObject>
    <description>Produkte, die von externen Partnern oder Assets in Media Transparency beworben werden.</description>
    <label>Advertised Media Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertised Media Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign.</description>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlightMotiveAllocation__c.object
<CustomObject>
    <description>Speichert die Zuordnung eines Motivs zu einem Flight und enthält zusätzliche, buchungsrelevante Informationen zur Ausstrahlung.</description>
    <fields>
        <fullName>MT_MediaFlight_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Flight, dem das Motiv zugeordnet wird.</description>
        <label>Media Flight</label>
        <referenceTo>MT_MediaFlight__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>MT_Media_Flight_Motive_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_MediaMotive_ref__c</fullName>
        <description>Das Motiv, das dem Flight zugeordnet wird.</description>
        <label>Media Motive</label>
        <referenceTo>MT_MediaMotive__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>MediaFlightMotiveAllocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>MT_MediaProduct_ref__c</fullName>
        <description>Das Produkt, dass in dieser Zuordnung gebucht wird. Kann von dem Master des Motivs abweichen (z.B. bei allgemeinen Remindern, die im Paket mit einem spezifischen Produkt verwendet werden).</description>
        <label>Advertised Media Product</label>
        <referenceTo>MT_AdvertisedMediaProduct__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>Media_Flight_Motive_Allocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Flight Motive Allocation</label>
    <nameField>
        <displayFormat>MFMA-{00000}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Flight Motive Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaMotive__c.object
<CustomObject>
    <description>Definiert ein Werbe-Motiv, das im TV ausgestrahlt werden kann. Die Datensätze werden über die Flightplanung gepflegt.</description>
    <label>Media Motive</label>
    <nameField>
        <label>Media Motive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Motives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaFlightMotiveAllocations.cls
/************************************************************************************************************
Name:  		MT_MediaFlightMotiveAllocations
======================================================
Purpose: 	Domain class for MT_MediaFlightMotiveAllocation__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
???			???							Created class
16.03.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public class MT_MediaFlightMotiveAllocations {
  private List<MT_MediaFlightMotiveAllocation__c> scope;

  public MT_MediaFlightMotiveAllocations(List<MT_MediaFlightMotiveAllocation__c> scope) {
    this.scope = scope;
  }

  public static MT_MediaFlightMotiveAllocation__c create(MT_MediaFlight__c mediaFlight, MT_MediaMotive__c mediaMotive, MT_AdvertisedMediaProduct__c mediaProduct) {
    return new MT_MediaFlightMotiveAllocation__c(
      MT_MediaFlight_ref__c = mediaFlight.Id,
      MT_MediaMotive_ref__c = mediaMotive.Id,
      MT_MediaProduct_ref__c = mediaProduct.Id
    );
  }

  public class MT_MediaFlightMotiveAllocationsException extends Exception {
  }
}