src/objects/MT_CampaignMonthlyPlanImportData__c.object
<CustomObject>
    <description>Import table for campaign monthly plan data from KRS.</description>
    <fields>
        <fullName>MT_Amount1__c</fullName>
        <label>Amount1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount2__c</fullName>
        <label>Amount2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount3__c</fullName>
        <label>Amount3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount4__c</fullName>
        <label>Amount4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_BMVSponsoringComplete__c</fullName>
        <label>BMV Sponsoring Complete</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_BMVSpotComplete__c</fullName>
        <label>BMV Spot Complete</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <label>CampaignId</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_DealProbabilitySpots__c</fullName>
        <label>Deal Probability Spots</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MT_Month__c</fullName>
        <label>Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_RevenueFix__c</fullName>
        <label>Revenue Fix</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign Monthly Plan Import Data</label>
    <nameField>
        <displayFormat>MCMPID-{00000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plan Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CampaignMPImportData.cls
/**
 * Domain class for MT_CampaignMonthlyPlanImportData__c object.
 *
 * @author GP
 */
public with sharing class MT_CampaignMPImportData {

  /**
   * Create a new record with the provided external keys
   * and internal references.
   *
   * @param krsId ID of KRS campaign
   * @param year of KRS campaign
   * @param month of KRS campaign
   * @param revenueFix of KRS campaign
   * @param amount1 of KRS campaign
   * @param amount2 of KRS campaign
   * @param amount3 of KRS campaign
   * @param amount4 of KRS campaign
   * @param bmvSponsoringComplete of KRS campaign
   * @param bmvSpotComplete of KRS campaign
   * @param dealProbabilitySpots of KRS campaign
   * 
   * @return new record
   */
  public static MT_CampaignMonthlyPlanImportData__c create( Integer krsId, Integer planYear, Integer planMonth, decimal revenueFix, 
                                                            Integer amount1, Integer amount2, Integer amount3, Integer amount4, 
                                                            decimal bmvSponsoringComplete, decimal bmvSpotComplete, decimal dealProbabilitySpots) {
    return new MT_CampaignMonthlyPlanImportData__c( MT_CampaignId__c=krsId, MT_Year__c=planYear, MT_Month__c=planMonth, MT_RevenueFix__c=revenueFix, 
                                                    MT_Amount1__c=amount1, MT_Amount2__c=amount2, MT_Amount3__c=amount3, MT_Amount4__c=amount4, 
                                                    MT_BMVSponsoringComplete__c=bmvSponsoringComplete, MT_BMVSpotComplete__c=bmvSpotComplete, MT_DealProbabilitySpots__c=dealProbabilitySpots);
  }
}