src/objects/MT_CampaignTypeParameterVersion__c.object
<CustomObject>
    <description>Hält wichtige Daten für den Media Monatsplan in Abhängigkeit zu den Kampagnentypen</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <description>Der Kamapgnentyp, zu dem diese Parameter gehören.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaign Type Parameter Version</relationshipLabel>
        <relationshipName>MediaCampaignType_ParameterVersion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_ValidFrom__c</fullName>
        <description>Der Monat, ab dem die Werte aus diesem Datensatz für die entsprechenden Kampagnen gelten.</description>
        <label>Geltungsdatum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Campaign Type Parameter Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Type Parameter Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_CampaignTypeParameterVersions.cls
/**
 * Domain class for CampaignTypeParameterVersion object
 *
 * History
 * -------
 * Date       AUTHOR            DETAIL
 * 04.05.2017 Falco Aulitzky    Initial architecture & development
 **/
public with sharing class MT_CampaignTypeParameterVersions {
  private List<MT_CampaignTypeParameterVersion__c> scope;

  public MT_CampaignTypeParameterVersions(List<MT_CampaignTypeParameterVersion__c> scope) {
    this.scope = scope;
  }

  public static MT_CampaignTypeParameterVersion__c create(MT_MediaCampaignType__c camType, Date validFrom) {
    return new MT_CampaignTypeParameterVersion__c(
      MT_MediaCampaignType_ref__c = camType.Id,
      MT_ValidFrom__c = validFrom);
  }

  public class MT_CampaignTypeParameterVersionsException extends Exception {
  }
}