src/objects/MT_CampaignImportData__c.object
<CustomObject>
    <description>Import table for campaign data from KRS.</description>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <description>KRS ID of campaign</description>
        <label>Campaign ID</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_OpportunitySalesforceId__c</fullName>
        <description>Salesforce ID of the opportunity related to the KRS campaign.</description>
        <label>Opportunity Salesforce ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign Import Data</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Transparency Campaign Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CampaignImportDataSelector_Test.cls
/**
 * Unit test for <code>MT_CampaignImportDataSelector</code> class.
 *
 * @author Fabio Andree Scheurel (MaibornWolff GmbH)
 */
@IsTest
private class MT_CampaignImportDataSelector_Test {
  @IsTest
  private static void testQueryLocatorForAll() {
    Set<String> fields = new Set<String> {
      MT_CampaignImportData__c.Id.getDescribe().getName(),
      MT_CampaignImportData__c.Name.getDescribe().getName(),
      MT_CampaignImportData__c.MT_CampaignId__c.getDescribe().getName(),
      MT_CampaignImportData__c.MT_OpportunitySalesforceId__c.getDescribe().getName()
    };

    MT_CampaignImportDataSelector sel = new MT_CampaignImportDataSelector();

    Test.startTest();
    Database.QueryLocator ql = sel.queryLocatorForAll(fields);
    Test.stopTest();

    System.assertNotEquals(null, ql, 'No query locator was returned');
    String query = ql.getQuery();

    System.assertEquals(true, query.contains(' FROM ' + MT_CampaignImportDataSelector.OBJECT_API_NAME), 'Query does not target the sObject ' + MT_CampaignImportDataSelector.OBJECT_API_NAME);

    for (String field : fields) {
      System.assertEquals(true, query.contains(field), 'Query does not select field ' + field);
    }
  }
}