src/objects/MT_CampaignImportData__c.object
<CustomObject>
    <description>Import table for campaign data from KRS.</description>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <description>KRS ID of campaign</description>
        <label>Campaign ID</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_OpportunitySalesforceId__c</fullName>
        <description>Salesforce ID of the opportunity related to the KRS campaign.</description>
        <label>Opportunity Salesforce ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign Import Data</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Transparency Campaign Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CampaignImportData_Test.cls
/**
 * Unit test for <code>MT_CampaignImportData</code> domain class.
 *
 * @author Fabio Andree Scheurel (MaibornWolff GmbH)
 */
@IsTest
private class MT_CampaignImportData_Test {
  @IsTest
  private static void testCreate() {
    Integer krsId = 42;
    Id opportunityId = Opportunity.SObjectType.getDescribe().getKeyPrefix() + '0'.repeat(15);

    Test.startTest();
    MT_CampaignImportData__c rec = MT_CampaignImportData.create(krsId, opportunityId);
    Test.stopTest();

    System.assertNotEquals(null, rec, 'No record was created');
    System.assertEquals(krsId, rec.MT_CampaignId__c, 'KRS ID is not set on new record');
    System.assertEquals(opportunityId, rec.MT_OpportunitySalesforceId__c, 'Salesforce Opportunity ID is not set on new record');
  }
}