src/objects/MT_CampaignMonthlyPlanImportData__c.object
<CustomObject>
    <description>Import table for campaign monthly plan data from KRS.</description>
    <fields>
        <fullName>MT_Amount1__c</fullName>
        <label>Amount1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount2__c</fullName>
        <label>Amount2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount3__c</fullName>
        <label>Amount3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount4__c</fullName>
        <label>Amount4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_BMVSponsoringComplete__c</fullName>
        <label>BMV Sponsoring Complete</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_BMVSpotComplete__c</fullName>
        <label>BMV Spot Complete</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <label>CampaignId</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_DealProbabilitySpots__c</fullName>
        <label>Deal Probability Spots</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MT_Month__c</fullName>
        <label>Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_RevenueFix__c</fullName>
        <label>Revenue Fix</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign Monthly Plan Import Data</label>
    <nameField>
        <displayFormat>MCMPID-{00000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plan Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_KRSID__c</fullName>
        <description>Enthält die ID aus dem Altsystem (KRS), wird beim Import befüllt.</description>
        <externalId>true</externalId>
        <label>KRS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <description>Ende des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <description>Start des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue1_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 1.</description>
        <label>Var. Umsatz 1 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue2_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 2.</description>
        <label>Var. Umsatz 2 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue3_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 3.</description>
        <label>Var. Umsatz 3 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue4_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 4.</description>
        <label>Var. Umsatz 4 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <fields>
        <fullName>MT_BMVSponsoring__c</fullName>
        <description>Hier kann im Businessplan das Sponsoring- BMV eingetragen werden.</description>
        <label>BMV Sponsoring</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_BMVSpot__c</fullName>
        <description>Hier kann im Businessplan das Spot- BMV eingetragen werden.</description>
        <label>BMV Spot</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_FixRevenue__c</fullName>
        <description>Speichert den ermittelten fixen Umsatz für diesen Monat(splan). Kann entweder die eingetragene monatliche Zahlung von der Kampagne sein oder das Ergebnis von monatliches BMV * Fix Yield von der Kampagne.</description>
        <label>Fix Revenue</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Monat(splan) gehört.</description>
        <label>Media Transparency Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>Media_Campaign_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Month__c</fullName>
        <description>Zahldarstellung des Monats (ohne Jahr). Wird in Custom Seiten (Businessplan, Flightplan) in JS verwendet.</description>
        <formula>MONTH(MT_PlanningDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Probability__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Die Wahrscheinlichkeit, dass das Spot- BMV des Monats abgerufen wird.</description>
        <label>Probability</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue1_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 1 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 1 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue2_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 2 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 2 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue3_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 3 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 3 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue4_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 4 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 4 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Year__c</fullName>
        <description>Zahldarstellung des Jahres (ohne Monat). Wird in Custom Seiten (Businessplan, Flightplan) in JS verwendet.</description>
        <formula>YEAR(MT_PlanningDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_CampMPImportDataTransformator_Test.cls
/**
 * Unit test for the <code>MT_CampMPImportDataTransformator</code>
 * batch job.
 *
 * @author GP
 */
@isTest
private class MT_CampMPImportDataTransformator_Test {

  @IsTest
  private static void testStart() {
    MT_CampMPImportDataTransformator batch = new MT_CampMPImportDataTransformator();

    Test.startTest();
    Object result = batch.start(null);
    Test.stopTest();

    System.assertEquals(true, result instanceof Database.QueryLocator, 'Batch.start() should but does not return a QueryLocator instance');
    Database.QueryLocator ql = (Database.QueryLocator) result;
    String query = ql.getQuery();

    String queryLocatorSobjectTarget = MT_CampaignMonthlyPlanImportData__c.getSObjectType().getDescribe().getName();
    System.assertEquals(true, query.contains(queryLocatorSobjectTarget), 'Batch.start() does not return a query on ' + queryLocatorSobjectTarget);

    FieldSet batchFields = SObjectType.MT_CampaignMonthlyPlanImportData__c.FieldSets.MT_TransformationBatchFields;
    for (FieldSetMember field : batchFields.getFields()) {
      System.assertEquals(true, query.contains(field.getFieldPath()), 'Batch.start() does not return a query that includes the field "' + field.getFieldPath() + '".');
    }
  }

  @IsTest
  private static void testFinish() {
    MT_Test.MockProvider mock = new MT_SystemEmailFactory_Test.MT_SystemEmailFactoryMockProvider();
    MT_SystemEmailFactory.INSTANCE = (MT_SystemEmailFactory) Test.createStub(MT_SystemEmailFactory.class, mock);

    MT_CampMPImportDataTransformator batch = new MT_CampMPImportDataTransformator();

    batch.processedRecords = 7;
    batch.updatedRecords = 3;
    batch.failedRecords = 4;
    batch.loggedErrors = new List<String>{
      'test 1',
      'test 2',
      'test 3'
    };

    Test.startTest();
    batch.finish(null);
    Test.stopTest();

    mock.assertMethodWasCalled(MT_SystemEmailFactory.getInstance(), MT_SystemEmailFactory_Test.MT_SYSTEMEMAILFACTORY_CREATE_MAIL_METHOD, 1);
    MT_SystemEmail mail = (MT_SystemEmail) mock.getInvocations(MT_SystemEmailFactory.getInstance(), MT_SystemEmailFactory_Test.MT_SYSTEMEMAILFACTORY_CREATE_MAIL_METHOD).get(0).getReturnValue();
    mock.assertMethodWasCalled(mail, MT_SystemEmail_Test.MT_SYSTEMEMAIL_SENDEMAIL_METHOD, 1);

    mock.assertMethodWasCalled(new MT_Test.MethodCall(MT_SystemEmailFactory.getInstance(), MT_SystemEmailFactory_Test.MT_SYSTEMEMAILFACTORY_CREATE_MAIL_METHOD, MT_SystemEmail.class, new List<Type>{
      Id.class
    }, new List<String>(), new List<Object>{
      UserInfo.getUserId()
    }));
    mock.assertMethodWasCalled(new MT_Test.MethodCall(mail, MT_SystemEmail_Test.MT_SYSTEMEMAIL_SUBJECT_METHOD, MT_SystemEmail.class, new List<Type>{
      String.class
    }, new List<String>(), new List<Object>{
      System.Label.MT_MP_ImportDataTransformator_EMAIL_ResultSubject
    }));
    String errors = '';
    for (String err : batch.loggedErrors) {
      errors += '- ' + err + '\n';
    }
    String body = String.format(System.Label.MT_MP_ImportDataTransformator_EMAIL_ResultBody, new List<String>{
      String.valueOf(batch.processedRecords),
      String.valueOf(batch.updatedRecords),
      String.valueOf(batch.failedRecords),
      errors
    });
    mock.assertMethodWasCalled(new MT_Test.MethodCall(mail, MT_SystemEmail_Test.MT_SYSTEMEMAIL_PLAINTEXTBODY_METHOD, MT_SystemEmail.class, new List<Type>{
      String.class
    }, new List<String>(), new List<Object>{
      body
    }));
  }

  @IsTest
  private static void testExecuteRecordsPurged() {
    MT_CampMPImportDataTransformator batch = new MT_CampMPImportDataTransformator();

    List<MT_CampaignMonthlyPlanImportData__c> testData = MT_Test.initCampaignMonthlyPlanImportTestData();
    System.assert(testData.size() > 0, 'TEST DATA FAILURE: there is no test data available!');

    Test.startTest();
    batch.execute(null, testData);
    Test.stopTest();

    System.assertEquals(
      false,
      new MT_CampaignMPImportDataSelector().queryLocatorForAll(new Set<String>{
        MT_CampaignMonthlyPlanImportData__c.Id.getDescribe().getName()
      }).iterator().hasNext(),
      'There is at least one record left over after the transformation batch run.'
    );
  }

  @IsTest
  private static void testExecuteMonthlyPlansUpdated() {
    MT_CampMPImportDataTransformator batch = new MT_CampMPImportDataTransformator();

    List<MT_CampaignMonthlyPlanImportData__c> testData = MT_Test.initCampaignMonthlyPlanImportTestData();
    System.assert(testData.size() > 0, 'TEST DATA FAILURE: there is no test data available');

    // FIXME add some special test cases here

    Test.startTest();
    batch.execute(null, testData);
    Test.stopTest();

    Set<String> krsIds = new Set<String>();
    for (MT_CampaignMonthlyPlanImportData__c rec : testData) {
      krsIds.add(String.valueOf(Integer.valueOf(rec.MT_CampaignId__c)));
    }

    Set<String> fields = new Set<String>{
      MT_MediaCampaignMonthlyPlan__c.MT_MediaCampaign_ref__c.getDescribe().getRelationshipName() + '.' + MT_MediaCampaign__c.MT_KRSID__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_Year__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_Month__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_FixRevenue__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_VariableRevenue1_SoldAmount__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_VariableRevenue2_SoldAmount__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_VariableRevenue3_SoldAmount__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_VariableRevenue4_SoldAmount__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_BMVSpot__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_BMVSponsoring__c.getDescribe().getName(),
      MT_MediaCampaignMonthlyPlan__c.MT_Probability__c.getDescribe().getName()
    };

    List<MT_MediaCampaignMonthlyPlan__c> monthlyPlans = new MT_MediaBuildingBlockMonthlyPlanSelector().getRecordsByKrsIds(krsIds, fields);
    Map<String, MT_MediaCampaignMonthlyPlan__c> monthlyPlanMap = new Map<String, MT_MediaCampaignMonthlyPlan__c>();
    for (MT_MediaCampaignMonthlyPlan__c monthlyPlan : monthlyPlans) {
      String key = monthlyPlan.MT_MediaCampaign_ref__r.MT_KRSID__c + '_' + String.valueOf(Integer.valueOf(monthlyPlan.MT_Year__c)) + '_' + String.valueOf(Integer.valueOf(monthlyPlan.MT_Month__c));
      monthlyPlanMap.put(key, monthlyPlan);
    }

    for (MT_CampaignMonthlyPlanImportData__c importRec : testData) {
      String key = String.valueOf(Integer.valueOf(importRec.MT_CampaignId__c)) + '_' + String.valueOf(Integer.valueOf(importRec.MT_Year__c)) + '_' + String.valueOf(Integer.valueOf(importRec.MT_Month__c));
      System.assertEquals(true, monthlyPlanMap.containsKey(key), 'For import record with key "' + key + '" there is no matching monthly plan in the system.');
      MT_MediaCampaignMonthlyPlan__c monthlyPlan = monthlyPlanMap.get(key);
      System.assertEquals(importRec.MT_RevenueFix__c, monthlyPlan.MT_FixRevenue__c, 'Fix revenue has not been updated!');
      System.assertEquals(importRec.MT_Amount1__c, monthlyPlan.MT_VariableRevenue1_SoldAmount__c, 'Sold Amount of Variable Revenue 1 has not been updated!');
      System.assertEquals(importRec.MT_Amount2__c, monthlyPlan.MT_VariableRevenue2_SoldAmount__c, 'Sold Amount of Variable Revenue 2 has not been updated!');
      System.assertEquals(importRec.MT_Amount3__c, monthlyPlan.MT_VariableRevenue3_SoldAmount__c, 'Sold Amount of Variable Revenue 3 has not been updated!');
      System.assertEquals(importRec.MT_Amount4__c, monthlyPlan.MT_VariableRevenue4_SoldAmount__c, 'Sold Amount of Variable Revenue 4 has not been updated!');
      System.assertEquals(importRec.MT_BMVSpotComplete__c, monthlyPlan.MT_BMVSpot__c, 'BMV Spot has not been updated!');
      System.assertEquals(importRec.MT_BMVSponsoringComplete__c, monthlyPlan.MT_BMVSponsoring__c, 'BMV Sponsoring has not been updated!');
      System.assertEquals(importRec.MT_DealProbabilitySpots__c, monthlyPlan.MT_Probability__c, 'Probability has not been updated!');
    }

    System.assertEquals(testData.size(), batch.processedRecords, 'Wrong number of import records have been processed.');
    System.assertEquals(testData.size(), batch.updatedRecords, 'Not all monthly plans were updated.');
    System.assertEquals(0, batch.failedRecords, 'No errors should occur, however there seem to be some.');
    System.assertEquals(new List<String>(), batch.loggedErrors, 'Some errors occurred.');
  }

  @IsTest
  private static void testExecuteMonthlyPlansNoMatch() {
    MT_CampMPImportDataTransformator batch = new MT_CampMPImportDataTransformator();

    List<MT_MediaCampaign__c> campaigns = new List<MT_MediaCampaign__c>{
      new MT_MediaCampaign__c(MT_KRSID__c = '123456', MT_RunTimeTVStart__c = Date.today().addMonths(-10), MT_RunTimeTVEnd__c = Date.today().addMonths(10)),
      new MT_MediaCampaign__c(MT_KRSID__c = '987654', MT_RunTimeTVStart__c = Date.today().addMonths(-10), MT_RunTimeTVEnd__c = Date.today().addMonths(10))
    };

    // we'll create import data for campaigns that do not exist in the database
    List<MT_CampaignMonthlyPlanImportData__c> importData = MT_Test.createCampaignMonthlyPlanImportData(campaigns);
    insert importData;

    Test.startTest();
    batch.execute(null, importData);
    Test.stopTest();

    System.assertEquals(importData.size(), batch.processedRecords, 'Wrong number of import records have been processed.');
    System.assertEquals(0, batch.updatedRecords, 'There have been updates although no records are there to be updated.');
    System.assertEquals(importData.size(), batch.failedRecords, 'Wrong number of failed records, all records should fail as there is no target record to update.');
  }
}