src/objects/MT_CampaignImportData__c.object
<CustomObject>
    <description>Import table for campaign data from KRS.</description>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <description>KRS ID of campaign</description>
        <label>Campaign ID</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_OpportunitySalesforceId__c</fullName>
        <description>Salesforce ID of the opportunity related to the KRS campaign.</description>
        <label>Opportunity Salesforce ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign Import Data</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Transparency Campaign Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CampaignImportData.cls
/**
 * Domain class for MT_CampaignImportData object.
 *
 * @author Fabio Andree Scheurel (MaibornWolff GmbH)
 */
public with sharing class MT_CampaignImportData {

  /**
   * Create a new record with the provided external keys
   * and internal references.
   *
   * @param krsId ID of KRS campaign
   * @param opportunityId Salesforce ID of opportunity that the
   * record is related to
   * @return new record
   */
  public static MT_CampaignImportData__c create(Integer krsId, Id opportunityId) {
    return new MT_CampaignImportData__c(MT_CampaignId__c = krsId, MT_OpportunitySalesforceId__c = opportunityId);
  }
}