src/objects/MT_CampaignTypeParameterVersion__c.object
<CustomObject>
    <description>Hält wichtige Daten für den Media Monatsplan in Abhängigkeit zu den Kampagnentypen</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <description>Der Kamapgnentyp, zu dem diese Parameter gehören.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaign Type Parameter Version</relationshipLabel>
        <relationshipName>MediaCampaignType_ParameterVersion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Campaign Type Parameter Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Type Parameter Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_CampTypeParameterVersionController.cls
/**
* Name:     MT_CampTypeParameterVersionController
* Purpose:  Controller for the page MT_ParameterVersions. 
*           It contains all the method for an angular app to access the sfdc db. Refered as Backend
*
* History
* -------
* DATE        AUTHOR                      DETAIL
* 04.05.2017  Falco Aulitzky              Initial architecture and development
*
*/
public with sharing class MT_CampTypeParameterVersionController {
  public MT_CampTypeParameterVersionController(ApexPages.StandardController stdController) {
  }

	/*
  	* Remote Action that is accessed by Javascript to load CampaignTypeParameterVersions and CampaignTypes
  	* 
  	* @returns  MT_CampTypeParameterVersionControllerDTO
  	*           Map<Id, List<MT_CampaignTypeParameterVersion__c>> campainTypesToParameterVersions maps CampaignType ids to lists of CampaignTypeParameterVersions
  	*/
  @RemoteAction
  public static MT_CampTypeParameterVersionControllerDTO loadParameterVersionsCombinedWithCampaignTypes() {
    return new MT_CampTypeParameterVersionControllerDTO().getParameterVersionsCombinedWithCampaignTypes(
      MT_CampaignTypeParameterVersionService.getCampaignTypeParameterVersions(),
      MT_MediaCampaignTypeService.getMediaCampaignTypes()
    );
  }

  public class MT_CampTypeParameterVersionControllerDTO {
    Map<Id, List<MT_CampaignTypeParameterVersion__c>> campaignTypesToParameterVersions;
    Map<Id, MT_MediaCampaignType__c> campaignTypeIdToCampaignTypeObject;

		/*
	    * Method to fill a map with data from the database
	    * 
	    * @param    List<MT_CampaignTypeParameterVersion__c> paraVersions gets the CampaignTypeParameterVersion objects
	    *			List<MT_MediaCampaignType__c> campaignTypes gets the MediaCampaignType objects
	    * @returns  MT_CampTypeParameterVersionControllerDTO with:
	    *           MediaCampaignType ids mapped to a list of CampaignTypeParameterVersion objects
	    */
    public MT_CampTypeParameterVersionControllerDTO getParameterVersionsCombinedWithCampaignTypes(List<MT_CampaignTypeParameterVersion__c> paraVersions, List<MT_MediaCampaignType__c> campaignTypes) {
      campaignTypesToParameterVersions = new Map<Id, List<MT_CampaignTypeParameterVersion__c>>();
      campaignTypeIdToCampaignTypeObject = new Map<Id, MT_MediaCampaignType__c>();

      for (MT_MediaCampaignType__c mct: campaignTypes) {

        if (!campaignTypesToParameterVersions.containsKey(mct.Id)) {
          campaignTypesToParameterVersions.put(mct.Id, new List<MT_CampaignTypeParameterVersion__c>());
        }

        campaignTypeIdToCampaignTypeObject.put(mct.Id, mct);

        for (MT_CampaignTypeParameterVersion__c pv: paraVersions) {
          if (pv.MT_MediaCampaignType_ref__c == mct.Id) {
            campaignTypesToParameterVersions.get(mct.Id).add(pv);
          }
        }
      }

      return this;
    }
  }
}