src/objects/MT_CampaignMonthlyPlanImportData__c.object
<CustomObject>
    <description>Import table for campaign monthly plan data from KRS.</description>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <label>CampaignId</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Month__c</fullName>
        <label>Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign Monthly Plan Import Data</label>
    <nameField>
        <displayFormat>MCMPID-{00000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plan Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CampaignMPImportDataSelector_Test.cls
/**
 * Unit test for <code>MT_CampaignMPImportDataSelector</code> class.
 *
 * @author GP
 */
@isTest
private class MT_CampaignMPImportDataSelector_Test {
@IsTest
  private static void testQueryLocatorForAll() {
    Set<String> fields = new Set<String> {
      MT_CampaignMonthlyPlanImportData__c.Id.getDescribe().getName(),
      MT_CampaignMonthlyPlanImportData__c.Name.getDescribe().getName(),
      MT_CampaignMonthlyPlanImportData__c.MT_CampaignId__c.getDescribe().getName(),
      MT_CampaignMonthlyPlanImportData__c.MT_Year__c.getDescribe().getName(),
      MT_CampaignMonthlyPlanImportData__c.MT_Month__c.getDescribe().getName()
    };

    MT_CampaignMPImportDataSelector sel = new MT_CampaignMPImportDataSelector();

    Test.startTest();
    Database.QueryLocator ql = sel.queryLocatorForAll(fields);
    Test.stopTest();

    System.assertNotEquals(null, ql, 'No query locator was returned');
    String query = ql.getQuery();

    System.assertEquals(true, query.contains(' FROM ' + MT_CampaignMPImportDataSelector.OBJECT_API_NAME), 'Query does not target the sObject ' + MT_CampaignMPImportDataSelector.OBJECT_API_NAME);

    for (String field : fields) {
      System.assertEquals(true, query.contains(field), 'Query does not select field ' + field);
    }
  }
	
}