src/objects/MT_CampaignImportData__c.object
<CustomObject>
    <description>Import table for campaign data from KRS.</description>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <description>KRS ID of campaign</description>
        <label>Campaign ID</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_CampaignName__c</fullName>
        <description>Name of KRS campaign</description>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MT_OpportunitySalesforceId__c</fullName>
        <description>Salesforce ID of the opportunity related to the KRS campaign.</description>
        <label>Opportunity Salesforce ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign Import Data</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Transparency Campaign Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_BmvTv__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Working value for the BMV (TV). Copied from the Opp Approval until approval is done, afterwards source of truth.</description>
        <label>BMV gesamt (TV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_KRSID__c</fullName>
        <description>Enthält die ID aus dem Altsystem (KRS), wird beim Import befüllt.</description>
        <externalId>true</externalId>
        <label>KRS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Typ dieser Kampagne. Steuert Konfigurationsparameter, z.B. Gewichtungsfaktoren, bei.</description>
        <label>Media Campaign Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4)) AND 5</booleanFilter>
            <errorMessage>Der ausgewählte Kampagnentyp ist inaktiv oder passt nicht zur Kampagne.</errorMessage>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_OpportunityApproval_ref__c</fullName>
        <description>Die Referenz zur Opportunity Freigabe, muss mit der referenzierten Opportunity übereinstimmen.</description>
        <label>Opportunity Freigabe</label>
        <referenceTo>P7S1_OpportunityApproval__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Opportunity_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Die Opportunity, zu der die Kampagne gehört. Per Validierungsregel wird sichergestellt, dass die Opportunity und Opportunity Freigabe zueinander gehören. Aus der Opportunity werden weitere Informationen gezogen, der Zugriff wird mit der direkten Referenz vereinfacht.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <description>Liefert den Namen des referenzierten Kampagnentypen, zur Vereinfachung der Einbindung (z.B. in Cockpit- Seiten, die nur die Kampagne laden).</description>
        <formula>MT_MediaCampaignType_ref__r.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <description>Das Asset, das diesen Kampagnentypen nutzt.</description>
        <label>Asset</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Media Campaign Types</relationshipLabel>
        <relationshipName>Media_Campaign_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Inaktive Typen können bei der Anlage von Kampagnen nicht mehr genutzt werden (Lookup- Filter)</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <description>Die Kategorie des Typs (intern / extern)</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Die Referenz zum internen Partner. Ersetzt mittelfristig die Pickliste P7S1_internerPartner__c. Soll genutzt werden, um Sharing zu steuern, außerdem als Verbindungspunkt für Kampagnentypen und weitere Einflussfaktoren auf die Kampagnen.</description>
        <label>Interner Partner (Asset)</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>MT_OpportunityApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CampaignImportDataTransformator.cls
/**
 * Batch that transform the imported campaign data from KRS
 * to Media Transparency campaigns in MT_Campaign__c.
 *
 * Note: This class is without sharing as it has to see
 * all data.
 *
 * @author Fabio Andree Scheurel (MaibornWolff GmbH)
 */

public without sharing class MT_CampaignImportDataTransformator implements Database.Batchable<sObject> {


  public Database.QueryLocator start(Database.BatchableContext bc) {
    FieldSet batchFields = SObjectType.MT_CampaignImportData__c.FieldSets.MT_TransformationBatchFields;
    return new MT_CampaignImportDataSelector().queryLocatorForAll(MT_FieldSet.getFields(batchFields));
  }


  public void execute(Database.BatchableContext bc, List<MT_CampaignImportData__c> scope) {
    try {
      doExecute(scope);
    } catch (Exception e) {
      System.debug(LoggingLevel.ERROR, e);
      //loggedErrors.add('Eine Ausnahme ist aufgetreten:\n' + e.getMessage());
      throw e;
    }
  }


  public void finish(Database.BatchableContext info) {
  }


  /**
   * Actual execution of imported data, will transform
   * the data and perform and upsert into the database.
   * The <code>importData</code> will be purged from
   * the database afterwards.
   *
   * Errors will be silently ignored!
   *
   * @param importData list of imported campaigns
   */
  private void doExecute(List<MT_CampaignImportData__c> importData) {
    Map<String,MT_MediaCampaign__c> campaignMap = getCampaignMapForReferencedCampaigns(importData);

    Map<Id,List<MT_MediaCampaign__c>> opptyIdToNewCampaignsMap = new Map<Id,List<MT_MediaCampaign__c>>();
    for (MT_CampaignImportData__c importDataRec : importData) {
      if (importDataRec.MT_CampaignId__c != null) {
        String krsId = String.valueOf(Integer.valueOf(importDataRec.MT_CampaignId__c));
        MT_MediaCampaign__c campaign = campaignMap.get(krsId);
        if (campaign == null) {
          campaign = MT_MediaCampaigns.create(
            new Opportunity(Id = importDataRec.MT_OpportunitySalesforceId__c),
            new P7S1_OpportunityApproval__c(),
            new MT_MediaCampaignType__c());
          campaign.MT_KRSID__c = krsId;
          campaign.RecordTypeId = MT_MediaCampaigns.getRecordTypeIdForExternalCampaign();
          campaign.MT_BmvTv__c = 1; // FIXME fill with import value once received from KRS with MT-679
          campaignMap.put(krsId, campaign);
          if (!opptyIdToNewCampaignsMap.containsKey(importDataRec.MT_OpportunitySalesforceId__c)) {
            opptyIdToNewCampaignsMap.put(importDataRec.MT_OpportunitySalesforceId__c, new List<MT_MediaCampaign__c>());
          }
          opptyIdToNewCampaignsMap.get(importDataRec.MT_OpportunitySalesforceId__c).add(campaign);
        }
        updateCampaign(campaign, importDataRec);
      }
    }


    enrichNewCampaignsWithOpportunityApprovalReference(opptyIdToNewCampaignsMap);

    System.debug(LoggingLevel.DEBUG, '### Transforming ' + importData.size() + ' imported records into media transparency campaigns.');
    List<Database.UpsertResult> results = Database.upsert(campaignMap.values(), false);
    System.debug(LoggingLevel.DEBUG, JSON.serializePretty(results));

    delete importData;
  }


  /**
   * Retrieves a map of the existing campaigns from the database,
   * identified by the KRS ID.
   *
   * @param importData imported campaign records
   * @return Map of KRS ID to Campaign
   */
  private Map<String,MT_MediaCampaign__c> getCampaignMapForReferencedCampaigns(List<MT_CampaignImportData__c> importData) {
    Set<String> krsIds = new Set<String>();
    for (MT_CampaignImportData__c importDataRec : importData) {
      if (importDataRec.MT_CampaignId__c != null) {
        krsIds.add(String.valueOf(Integer.valueOf(importDataRec.MT_CampaignId__c)));
      }
    }

    Map<String,MT_MediaCampaign__c> campaignMap = new Map<String,MT_MediaCampaign__c>();
    Set<String> mediaCampaignFields = new Set<String> {
      MT_MediaCampaign__c.Id.getDescribe().getName(),
      MT_MediaCampaign__c.Name.getDescribe().getName(),
      MT_MediaCampaign__c.MT_KRSID__c.getDescribe().getName(),
      MT_MediaCampaign__c.MT_Opportunity_ref__c.getDescribe().getName(),
      MT_MediaCampaign__c.MT_OpportunityApproval_ref__c.getDescribe().getName()
    };
    for (MT_MediaCampaign__c campaign : (List<MT_MediaCampaign__c>) new MT_MediaCampaignSelector().getRecordsByKrsIds(krsIds, mediaCampaignFields)) {
      campaignMap.put(campaign.MT_KRSId__c, campaign);
    }
    return campaignMap;
  }


  /**
   * Updates the <campaign> with the imported values from
   * <code>importCampaign</code>.
   *
   * @param campaign Campaign to updated
   * @param importCampaign values to use for update
   */
  private void updateCampaign(MT_MediaCampaign__c campaign, MT_CampaignImportData__c importCampaign) {
    campaign.Name = importCampaign.MT_CampaignName__c != null ? importCampaign.MT_CampaignName__c.left(MT_MediaCampaign__c.Name.getDescribe().getLength()) : null;
  }


  /**
   * Adds the Opportunity Approval reference (i.e. the ID) to
   * the provided Media Campaigns.
   * If the opportunity does not exist or does not have an
   * opportunity approval assigned, the campaign will not be
   * updated. If there are multiple approvals per opportunity
   * any of these will be taken.
   *
   * @param opptyIdToNewCampaignsMap Map of Opportunity ID to a
   * list of campaigns that are assigned to this opportunity
   */
  private void enrichNewCampaignsWithOpportunityApprovalReference(Map<Id,List<MT_MediaCampaign__c>> opptyIdToNewCampaignsMap) {
    Set<String> oppApprovalFields = new Set<String> {
      P7S1_OpportunityApproval__c.Id.getDescribe().getName(),
      P7S1_OpportunityApproval__c.P7S1_Opportunity__c.getDescribe().getName(),
      // BEGIN TEMPORARY WORKAROUND
      P7S1_OpportunityApproval__c.MT_Asset_ref__c.getDescribe().getName()
      // END TEMPORARY WORKAROUND
    };

    // BEGIN TEMPORARY WORKAROUND
    Set<Id> assetIds = new Set<Id>();
    // END TEMPORARY WORKAROUND
    for (P7S1_OpportunityApproval__c approval : new MT_OpportunityApprovalSelector().getRecordsByParentIds(opptyIdToNewCampaignsMap.keySet(), oppApprovalFields)) {
      if (opptyIdToNewCampaignsMap.containsKey(approval.P7S1_Opportunity__c)) {
        // BEGIN TEMPORARY WORKAROUND
        assetIds.add(approval.MT_Asset_ref__c);
        // END TEMPORARY WORKAROUND
        for (MT_MediaCampaign__c campaign : opptyIdToNewCampaignsMap.get(approval.P7S1_Opportunity__c)) {
          campaign.MT_OpportunityApproval_ref__c = approval.Id;
          campaign.MT_OpportunityApproval_ref__r = approval;
        }
      }
    }

    // BEGIN TEMPORARY WORKAROUND: Set campaign type based on opportunity approval until we get it from KRS
    Set<String> campaignTypeFields = new Set<String> {
      MT_MediaCampaignType__c.Id.getDescribe().getName(),
      MT_MediaCampaignType__c.MT_Type__c.getDescribe().getName(),
      MT_MediaCampaignType__c.MT_IsActive__c.getDescribe().getName(),
      MT_MediaCampaignType__c.MT_Asset_ref__c.getDescribe().getName()
    };
    Map<Id,Id> assetIdToMediaCampaignTypeIdMap = new Map<Id,Id>();
    for (MT_MediaCampaignType__c mct : (List<MT_MediaCampaignType__c>) new MT_MediaCampaignTypeSelector().getRecordsByAssetIds(assetIds, campaignTypeFields)) {
      if (mct.MT_Type__c == 'External' && mct.MT_IsActive__c == true) {
        assetIdToMediaCampaignTypeIdMap.put(mct.MT_Asset_ref__c, mct.Id);
      }
    }
    for (List<MT_MediaCampaign__c> campaigns : opptyIdToNewCampaignsMap.values()) {
      for (MT_MediaCampaign__c campaign : campaigns) {
        campaign.MT_MediaCampaignType_ref__c = assetIdToMediaCampaignTypeIdMap.get(campaign.MT_OpportunityApproval_ref__r.MT_Asset_ref__c);
      }
    }
    // END TEMPRORARY WORKAROUND
  }
}