src/objects/MT_CampaignTypeParameterVersion__c.object
<CustomObject>
    <description>Hält wichtige Daten für den Media Monatsplan in Abhängigkeit zu den Kampagnentypen</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <description>Der Kamapgnentyp, zu dem diese Parameter gehören.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaign Type Parameter Version</relationshipLabel>
        <relationshipName>MediaCampaignType_ParameterVersion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Media Campaign Type Parameter Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Type Parameter Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Typ dieser Kampagne. Steuert Konfigurationsparameter, z.B. Gewichtungsfaktoren, bei.</description>
        <label>Media Campaign Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4)) AND 5</booleanFilter>
            <errorMessage>Der ausgewählte Kampagnentyp ist inaktiv oder passt nicht zur Kampagne.</errorMessage>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <fields>
        <fullName>MT_MediaCampaignTypeParameterVersion_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Die Referenz wird per Trigger (Erstellen des Monatsplans), bzw. Batchjob (Erstellen einer neuen Version) befüllt. An Hand des Datumsvergleichs suchen sich beide Stellen die für den Monat(splan) gültige Version und ordnen diese zu.</description>
        <label>Media Campaign Type Parameter Version</label>
        <referenceTo>MT_CampaignTypeParameterVersion__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>MT_MediaCampaignMonthlyPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Monat(splan) gehört.</description>
        <label>Media Transparency Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>Media_Campaign_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <description>Der Monat, für den dieser Monatsplan gilt.</description>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_AssignCampTypeVersionToMonthlyPlans.cls
/*
* Name:     MT_AssignCampTypeVersionToMonthlyPlans
* Purpose:  Batch job; As soon as a Media Campaign Type Parameter Version is created this class
*           queries all Media Building Block Monthly Plans and updates the lookup field to the proper one, in regards of the valid date.
*
* History
* -------
* DATE        AUTHOR                      DETAIL
* 28.04.2017  Falco Aulitzky              Initial architecture and development
*
*/
global without sharing class MT_AssignCampTypeVersionToMonthlyPlans extends MT_Selector implements Database.Batchable<sObject> {

  Map<Id, Set<MT_CampaignTypeParameterVersion__c>> mctIdsToPvs;
  Set<Id> mctIds;
  String query;

    /*
    * Queries MediaBuildingBlockMonthlyPlan objects that need to be updated
    *
    * @param    Map<Id, List<MT_CampaignTypeParameterVersion__c>> mctIdsToPvs: Map from MediaCampaignType ids to MediaCampaignTypeParameterVersion objects
    *           Date mctpvValidFromDate: MediaCampaignTypeParameterVersion earliestDate
    *           Date mctpvValidToDate: MediaCampaignTypeParameterVersion latestDate
    *
    */
  global MT_AssignCampTypeVersionToMonthlyPlans(Map<Id, Set<MT_CampaignTypeParameterVersion__c>> mctIdsToPvs, Date mctpvValidFromDate, Date mctpvValidToDate) {
    this.mctIdsToPvs = mctIdsToPvs;
    this.mctIds = mctIdsToPvs.keySet();
    String fromDate = ((mctpvValidFromDate + '').split(' ')).get(0);
    String toDate = ((mctpvValidToDate + '').split(' ')).get(0);

    if (mctpvValidToDate != null) {
      this.query = 'SELECT Id, MT_PlanningDate__c, MT_MediaCampaignTypeParameterVersion_ref__c, MT_MediaCampaign_ref__r.MT_MediaCampaignType_ref__c FROM MT_MediaCampaignMonthlyPlan__c WHERE MT_MediaCampaign_ref__r.MT_MediaCampaignType_ref__c in ' + constructInClauseString(mctIds) + ' AND MT_PlanningDate__c >= ' + fromDate + ' AND MT_PlanningDate__c < ' + toDate + ' ORDER BY MT_PlanningDate__c ASC';
    } else {
      this.query = 'SELECT Id, MT_PlanningDate__c, MT_MediaCampaignTypeParameterVersion_ref__c, MT_MediaCampaign_ref__r.MT_MediaCampaignType_ref__c FROM MT_MediaCampaignMonthlyPlan__c WHERE MT_MediaCampaign_ref__r.MT_MediaCampaignType_ref__c in ' + constructInClauseString(mctIds) + ' AND MT_PlanningDate__c >= ' + fromDate + ' ORDER BY MT_PlanningDate__c ASC';
    }

  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    System.debug('Batch start: ' + query);
    return Database.getQueryLocator(this.query);
  }

    /*
    * Compares Dates to figure out which MediaCampaignTypeParameterVersion belongs to which MediaBuildingBlockMonthlyPlan in regards to the MediaCampaignType id
    *
    * @param    List<sObject> scope : List of queried sObject
    *
    */
  global void execute(Database.BatchableContext BC, List<sObject> scope) {
    Map<Id, MT_MediaCampaignMonthlyPlan__c> toBeUpdatedMap = new Map<Id, MT_MediaCampaignMonthlyPlan__c>();

    for (sObject obj: scope) {
      MT_MediaCampaignMonthlyPlan__c toBeUpdated = (MT_MediaCampaignMonthlyPlan__c) obj;

      for (MT_CampaignTypeParameterVersion__c pv: mctIdsToPvs.get(toBeUpdated.MT_MediaCampaign_ref__r.MT_MediaCampaignType_ref__c)) {
        toBeUpdated.MT_MediaCampaignTypeParameterVersion_ref__c = pv.Id;

        toBeUpdatedMap.put(toBeUpdated.id, toBeUpdated);
      }
    }
    upsert toBeUpdatedMap.values();
  }

  global void finish(Database.BatchableContext BC) {
  }
}