src/objects/MT_CampaignTypeParameterVersion__c.object
<CustomObject>
    <description>Hält wichtige Daten für den Media Monatsplan in Abhängigkeit zu den Kampagnentypen</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <description>Der Kamapgnentyp, zu dem diese Parameter gehören.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaign Type Parameter Version</relationshipLabel>
        <relationshipName>MediaCampaignType_ParameterVersion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_ValidFrom__c</fullName>
        <description>Der Monat, ab dem die Werte aus diesem Datensatz für die entsprechenden Kampagnen gelten.</description>
        <label>Geltungsdatum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Campaign Type Parameter Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Type Parameter Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Typ dieser Kampagne. Steuert Konfigurationsparameter, z.B. Gewichtungsfaktoren, bei.</description>
        <label>Media Campaign Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4)) AND 5</booleanFilter>
            <errorMessage>Der ausgewählte Kampagnentyp ist inaktiv oder passt nicht zur Kampagne.</errorMessage>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <fields>
        <fullName>MT_MediaCampaignTypeParameterVersion_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Die Referenz wird per Trigger (Erstellen des Monatsplans), bzw. Batchjob (Erstellen einer neuen Version) befüllt. An Hand des Datumsvergleichs suchen sich beide Stellen die für den Monat(splan) gültige Version und ordnen diese zu.</description>
        <label>Media Campaign Type Parameter Version</label>
        <referenceTo>MT_CampaignTypeParameterVersion__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>MT_MediaCampaignMonthlyPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Monat(splan) gehört.</description>
        <label>Media Transparency Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>Media_Campaign_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <description>Der Monat, für den dieser Monatsplan gilt.</description>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_BuildingBlockMonthPlan_TriggerHandler.cls
/*
* Name:     MT_BuildingBlockMonthPlan_TriggerHandler
* Purpose:  Trigger; As soon as a Building Block Monthly Plan object is created and nearly saved, the trigger is called.
*           It then will compare Monthly Plans to Parameter Versions and their time frame, when the range passes the PV is stored as a reference on the Plan
* History
* -------
* DATE        AUTHOR                      DETAIL
* 28.04.2017  Falco Aulitzky              Initial architecture and development
*
*/
public with sharing class MT_BuildingBlockMonthPlan_TriggerHandler extends TriggerController {
  public MT_BuildingBlockMonthPlan_TriggerHandler(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
    List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
    super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
  }

    /* Finds the right Parameter Version for each created Monthly Plan */
  public override void runBeforeInsert() {
    List<MT_MediaCampaignMonthlyPlan__c> mbbmps = ((List<MT_MediaCampaignMonthlyPlan__c>) lstNewItems);
    Map<Id, List<MT_MediaCampaignMonthlyPlan__c>> mctIdsToMbbmp = new Map<Id, List<MT_MediaCampaignMonthlyPlan__c>>();
    List<Id> mcIds = new List<Id>();

    for (MT_MediaCampaignMonthlyPlan__c mbbmp: mbbmps) {
      mcIds.add(mbbmp.MT_MediaCampaign_ref__c);
    }

    Map<ID, MT_MediaCampaign__c> mcs = new Map<ID,MT_MediaCampaign__c>(MT_MediaCampaignService.getMediaCampaignsByIds(new Set<Id>(mcIds), new Set<String>{
      'Id', 'MT_MediaCampaignType_ref__c'
    }));


    for (MT_MediaCampaignMonthlyPlan__c mbbmp: mbbmps) {

      MT_MediaCampaign__c mc = mcs.get(mbbmp.MT_MediaCampaign_ref__c);

      if (!mctIdsToMbbmp.containsKey(mc.MT_MediaCampaignType_ref__c)) {
        mctIdsToMbbmp.put(mc.MT_MediaCampaignType_ref__c, new List<MT_MediaCampaignMonthlyPlan__c>());
      }

      mctIdsToMbbmp.get(mc.MT_MediaCampaignType_ref__c).add(mbbmp);
    }

    List<MT_CampaignTypeParameterVersion__c> ctpvs = [SELECT Id, MT_MediaCampaignType_ref__c, MT_ValidFrom__c FROM MT_CampaignTypeParameterVersion__c WHERE MT_MediaCampaignType_ref__c IN :mctIdsToMbbmp.keySet() ORDER BY MT_ValidFrom__c ASC];

    for (MT_CampaignTypeParameterVersion__c ctpv: ctpvs) {
      for (MT_MediaCampaignMonthlyPlan__c mbbp: mctIdsToMbbmp.get(ctpv.MT_MediaCampaignType_ref__c)) {
        if (ctpv.MT_ValidFrom__c <= mbbp.MT_PlanningDate__c) {
          mbbp.MT_MediaCampaignTypeParameterVersion_ref__c = ctpv.Id;
        }
      }
    }
  }
}