src/objects/MT_CampaignMonthlyPlanImportData__c.object
<CustomObject>
    <description>Import table for campaign monthly plan data from KRS.</description>
    <fields>
        <fullName>MT_Amount1__c</fullName>
        <label>Amount1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount2__c</fullName>
        <label>Amount2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount3__c</fullName>
        <label>Amount3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Amount4__c</fullName>
        <label>Amount4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_BMVSponsoringComplete__c</fullName>
        <label>BMV Sponsoring Complete</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_BMVSpotComplete__c</fullName>
        <label>BMV Spot Complete</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_CampaignId__c</fullName>
        <label>CampaignId</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_DealProbabilitySpots__c</fullName>
        <label>Deal Probability Spots</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MT_Month__c</fullName>
        <label>Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_RevenueFix__c</fullName>
        <label>Revenue Fix</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign Monthly Plan Import Data</label>
    <nameField>
        <displayFormat>MCMPID-{00000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plan Import Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_KRSID__c</fullName>
        <description>Enthält die ID aus dem Altsystem (KRS), wird beim Import befüllt.</description>
        <externalId>true</externalId>
        <label>KRS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue1_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 1.</description>
        <label>Var. Umsatz 1 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue2_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 2.</description>
        <label>Var. Umsatz 2 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue3_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 3.</description>
        <label>Var. Umsatz 3 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue4_SoldAmount__c</fullName>
        <description>Die erwartete Anzahl verkaufter Einheiten für die Umsatzbeteiligungskomponente 4.</description>
        <label>Var. Umsatz 4 - Verkaufte Anzahl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <fields>
        <fullName>MT_BMVSponsoring__c</fullName>
        <description>Hier kann im Businessplan das Sponsoring- BMV eingetragen werden.</description>
        <label>BMV Sponsoring</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_BMVSpot__c</fullName>
        <description>Hier kann im Businessplan das Spot- BMV eingetragen werden.</description>
        <label>BMV Spot</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_FixRevenue__c</fullName>
        <description>Speichert den ermittelten fixen Umsatz für diesen Monat(splan). Kann entweder die eingetragene monatliche Zahlung von der Kampagne sein oder das Ergebnis von monatliches BMV * Fix Yield von der Kampagne.</description>
        <label>Fix Revenue</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Monat(splan) gehört.</description>
        <label>Media Transparency Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>Media_Campaign_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Month__c</fullName>
        <description>Zahldarstellung des Monats (ohne Jahr). Wird in Custom Seiten (Businessplan, Flightplan) in JS verwendet.</description>
        <formula>MONTH(MT_PlanningDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <description>Der Monat, für den dieser Monatsplan gilt.</description>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_Probability__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Die Wahrscheinlichkeit, dass das Spot- BMV des Monats abgerufen wird.</description>
        <label>Probability</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue1_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 1 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 1 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue2_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 2 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 2 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue3_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 3 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 3 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue4_SoldAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Die Anzahl verkaufter Einheiten der Umsatzbeteiligungskomponente 4 in diesem Monat. Wird im Businessplan eingetragen.</description>
        <label>Var. Umsatz 4 - Verkaufte Einheiten</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_Year__c</fullName>
        <description>Zahldarstellung des Jahres (ohne Monat). Wird in Custom Seiten (Businessplan, Flightplan) in JS verwendet.</description>
        <formula>YEAR(MT_PlanningDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_CampMPImportDataTransformator.cls
/**
 * Batch that transform the imported campaign monthly plan data from KRS
 * to Media campaign Monthly Plans in MT_MediaCampaignMonthlyPlan__c.
 *
 * @author GP
 */

public with sharing class MT_CampMPImportDataTransformator implements Database.Batchable<sObject>, Database.Stateful {

  @TestVisible public List<String> loggedErrors;
  @TestVisible public Integer updatedRecords;
  @TestVisible public Integer processedRecords;
  @TestVisible public Integer failedRecords;

	/**
   * Initialize this instance.
   */
  public MT_CampMPImportDataTransformator() {
    loggedErrors = new List<String>();
    updatedRecords = 0;
    processedRecords = 0;
    failedRecords = 0;
  }

  /**
   * Query the affected records for transformation
   *
   * @param bc The execution context
   *
   * @return Database.QueryLocator
   */
  public Database.QueryLocator start(Database.BatchableContext bc) {
    FieldSet batchFields = SObjectType.MT_CampaignMonthlyPlanImportData__c.FieldSets.MT_TransformationBatchFields;
    return new MT_CampaignMPImportDataSelector().queryLocatorForAll(MT_FieldSet.getFields(batchFields));
  }

  /**
   * Execute the actual transformation on a chunk of the records.
   *
   * @param bc The execution context
   * @param scope The records to transform
   */
  public void execute(Database.BatchableContext bc, List<MT_CampaignMonthlyPlanImportData__c> scope) {
    try {
      doExecute(scope);
    } catch (Exception e) {
      System.debug(LoggingLevel.ERROR, e);
      loggedErrors.add('Eine Ausnahme ist aufgetreten:\n' + e.getMessage());
      throw e;
    }
  }


  /**
   * Finish the process by sending the email notification to the user.
   *
   * @param bc The execution context
   *
   */
  public void finish(Database.BatchableContext info) {
    String errorList = '';
    if (loggedErrors != null && !loggedErrors.isEmpty()) {
      errorList = '- ' + String.join(loggedErrors, '\n- ') + '\n';
    }

    String body = String.format(System.Label.MT_MP_ImportDataTransformator_EMAIL_ResultBody, new List<String>{
      String.valueOf(processedRecords),
      String.valueOf(updatedRecords),
      String.valueOf(failedRecords),
      errorList
    });

    MT_SystemEmailFactory.getInstance().createNewSystemEmailFor(UserInfo.getUserId()).
      saveAsActivity(false).
      subject(System.Label.MT_MP_ImportDataTransformator_EMAIL_ResultSubject).
      plainTextBody(body).
      treatBodiesAsTemplate(false).
      sendEmail();
  }


  /**
   * Actual execution of imported data, will transform
   * the data and perform and upsert into the database.
   * The <code>importData</code> will be purged from
   * the database afterwards.
   * 
   * Importkey is the key concatenated string using KRSID + Year + Month from MT_CampaignMonthlyPlanImportData__c object, Looks like 1234_2017_08
   *
   * Errors will be silently ignored!
   *
   * @param importData list of imported campaign monthly plans
   */
  private void doExecute(List<MT_CampaignMonthlyPlanImportData__c> importData) {
    Map<String, MT_MediaCampaignMonthlyPlan__c> campaignMonthlyPlanMap = getMonthlyPlansForCampaigns(importData);
    List<MT_MediaCampaignMonthlyPlan__c> monthlyPlansToBeUpdated = new List<MT_MediaCampaignMonthlyPlan__c>();
    List<MT_CampaignMonthlyPlanImportData__c> processedMpImportRecToDelete = new List<MT_CampaignMonthlyPlanImportData__c>();
    processedRecords = importData.size();

    for (MT_CampaignMonthlyPlanImportData__c monthlyPlanImportRec : importData) {
      String importKey = String.valueOf(Integer.valueOf(monthlyPlanImportRec.MT_CampaignId__c)) + '_' + String.valueOf(Integer.valueOf(monthlyPlanImportRec.MT_Year__c)) + '_' + String.valueOf(Integer.valueOf(monthlyPlanImportRec.MT_Month__c));
      if (campaignMonthlyPlanMap != null && campaignMonthlyPlanMap.containsKey(importKey) && monthlyPlanImportRec.MT_CampaignId__c != null && monthlyPlanImportRec.MT_Year__c != null && monthlyPlanImportRec.MT_Month__c != null) {
        MT_MediaCampaignMonthlyPlan__c monthlyPlanRec = campaignMonthlyPlanMap.get(importKey);
        monthlyPlanRec.MT_BMVSponsoring__c = monthlyPlanImportRec.MT_BMVSponsoringComplete__c != null ? monthlyPlanImportRec.MT_BMVSponsoringComplete__c : 0 ;
        monthlyPlanRec.MT_BMVSpot__c = monthlyPlanImportRec.MT_BMVSpotComplete__c != null ? monthlyPlanImportRec.MT_BMVSpotComplete__c : 0 ;
        monthlyPlanRec.MT_FixRevenue__c = monthlyPlanImportRec.MT_RevenueFix__c != null ? monthlyPlanImportRec.MT_RevenueFix__c : 0 ;
        monthlyPlanRec.MT_VariableRevenue1_SoldAmount__c = monthlyPlanImportRec.MT_Amount1__c != null ? monthlyPlanImportRec.MT_Amount1__c : 0 ;
        monthlyPlanRec.MT_VariableRevenue2_SoldAmount__c = monthlyPlanImportRec.MT_Amount2__c != null ? monthlyPlanImportRec.MT_Amount2__c : 0 ;
        monthlyPlanRec.MT_VariableRevenue3_SoldAmount__c = monthlyPlanImportRec.MT_Amount3__c != null ? monthlyPlanImportRec.MT_Amount3__c : 0;
        monthlyPlanRec.MT_VariableRevenue4_SoldAmount__c = monthlyPlanImportRec.MT_Amount4__c != null ? monthlyPlanImportRec.MT_Amount4__c : 0;
        monthlyPlanRec.MT_Probability__c = monthlyPlanImportRec.MT_DealProbabilitySpots__c != null ? monthlyPlanImportRec.MT_DealProbabilitySpots__c : 0 ;

        monthlyPlansToBeUpdated.add(monthlyPlanRec);
      } else {
        //Below will be moved to Error report object in an upcoming user story
        loggedErrors.add(System.Label.MT_MP_ImportDataTransformator_MonthlyPlan_NotFound_Error + importKey);
        failedRecords++;

      }
      processedMpImportRecToDelete.add(monthlyPlanImportRec);
    }

    if (!monthlyPlansToBeUpdated.isEmpty()) {
      updatedRecords += monthlyPlansToBeUpdated.size();
      Update monthlyPlansToBeUpdated;
    }

    if (!processedMpImportRecToDelete.isEmpty()) {
      Delete processedMpImportRecToDelete;
    }

  }

   /**
   * Retrieves a map of the existing campaign monthly plans to be updated
   * identified by their key, which is the concatenated string using
   * KRSID + Year + Month from MT_MediaCampaignMonthlyPlan__c object, looks
   * like 1234_2017_08.
   *
   * @param importData imported campaign monthly plan records
   * @return Map of monthlyPlanKey(krsid_year_month) to Campaign monthly plans
   */
  private Map<String, MT_MediaCampaignMonthlyPlan__c> getMonthlyPlansForCampaigns(List<MT_CampaignMonthlyPlanImportData__c> importData) {
    Set<String> krsIds = new Set<String>();
    Map<String, MT_MediaCampaignMonthlyPlan__c> campaignMpMap = new Map<String, MT_MediaCampaignMonthlyPlan__c>();
    for (MT_CampaignMonthlyPlanImportData__c importDataRec : importData) {
      if (importDataRec.MT_CampaignId__c != null) {
        krsIds.add(String.valueOf(Integer.valueOf(importDataRec.MT_CampaignId__c)));
      }
    }

    FieldSet batchFields = SObjectType.MT_MediaCampaignMonthlyPlan__c.FieldSets.MT_TransformationBatchFields;

    for (MT_MediaCampaignMonthlyPlan__c campaignMonthlyPlan : (List<MT_MediaCampaignMonthlyPlan__c>) new MT_MediaBuildingBlockMonthlyPlanSelector().getRecordsByKrsIds(krsIds, MT_FieldSet.getFields(batchFields))) {
      if (campaignMonthlyPlan.MT_MediaCampaign_ref__r.MT_KRSID__c != null && campaignMonthlyPlan.MT_MediaCampaign_ref__r.MT_KRSID__c != '' && campaignMonthlyPlan.MT_PlanningDate__c != null) {
        String monthlyPlanKey;
        monthlyPlanKey = campaignMonthlyPlan.MT_MediaCampaign_ref__r.MT_KRSID__c + '_' + String.valueOf(campaignMonthlyPlan.MT_PlanningDate__c.year()) + '_' + String.valueOf(campaignMonthlyPlan.MT_PlanningDate__c.month());
        campaignMpMap.put(monthlyPlanKey, campaignMonthlyPlan);
      }
    }

    return campaignMpMap;
  }

}