src/objects/MT_ForecastValue__c.object
<CustomObject>
    <description>Speichert die erwarteten BMV- Werte, die ein Asset in den jeweiligen Monaten für den referenzierten Kampagnentypen erwartet.</description>
    <fields>
        <fullName>MT_MediaCampaignType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Kampagnentyp, für den die Werte erwartet werden.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Forecast Values</relationshipLabel>
        <relationshipName>Media_Forecast_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Forecast Value</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaignTypeService.cls
/************************************************************************************************************
Name:  		MT_MediaCampaignTypeService
======================================================
Purpose: 	Service class for MT_MediaCampaignType__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
08.03.2017	Falco Aulitzky              Initial architecture & development
*************************************************************************************************************/
global with sharing class MT_MediaCampaignTypeService {

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypes() {
    return MT_MediaCampaignTypeService.getMediaCampaignTypes(
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypes(Set<String> fields) {
    return new MT_MediaCampaignTypeSelector().getRecords(
      fields
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesByIds(Set<Id> recordIds) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsByIds(
      recordIds,
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsByIds(
      recordIds,
      fields
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesByisActive(Boolean isActive) {
    if (isActive == null) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsByIsActive(
      isActive,
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesByisActive(Boolean isActive, Set<String> fields) {
    if (isActive == null) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsByIsActive(
      isActive,
      fields
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesByAssetIds(Set<Id> assetIds) {
    if (assetIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsByAssetIds(
      assetIds,
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesByAssetIds(Set<Id> assetIds, Set<String> fields) {
    if (assetIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsByAssetIds(
      assetIds,
      fields
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesWithMediaForecastValuesByIds(Set<Id> recordIds) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsWithMediaForecastValuesByIds(
      recordIds,
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields),
      MT_FieldSet.getFields(SObjectType.MT_ForecastValue__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesWithMediaForecastValuesByIds(Set<Id> recordIds, Set<String> mediaCampaignTypefields, Set<String> forecastValuefields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsWithMediaForecastValuesByIds(
      recordIds,
      mediaCampaignTypefields,
      forecastValuefields
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesWithMediaTransparencyCampaignsByIds(Set<Id> recordIds) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsWithMediaTransparencyCampaignsByIds(
      recordIds,
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields),
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaign__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesWithMediaTransparencyCampaignsByIds(Set<Id> recordIds, Set<String> mediaCampaignTypefields, Set<String> mediaTransparencyCampaignFields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsWithMediaTransparencyCampaignsByIds(
      recordIds,
      mediaCampaignTypefields,
      mediaTransparencyCampaignFields
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesWithForecastValueAndMediaTransCampaignsByIds(Set<Id> recordIds) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsWithForecastValueAndMediaTransCampaignsByIds(
      recordIds,
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaignType__c.FieldSets.MT_ContextFields),
      MT_FieldSet.getFields(SObjectType.MT_ForecastValue__c.FieldSets.MT_ContextFields),
      MT_FieldSet.getFields(SObjectType.MT_MediaCampaign__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<MT_MediaCampaignType__c> getMediaCampaignTypesWithForecastValueAndMediaTransCampaignsByIds(Set<Id> recordIds, Set<String> mediaCampaignTypefields, Set<String> forecastValuefields, Set<String> mediaTransparencyCampaignFields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_MediaCampaignTypeSelector().getRecordsWithForecastValueAndMediaTransCampaignsByIds(
      recordIds,
      mediaCampaignTypefields,
      forecastValuefields,
      mediaTransparencyCampaignFields
    );
  }
}