src/objects/MT_ForecastValue__c.object
<CustomObject>
    <description>Speichert die erwarteten BMV- Werte, die ein Asset in den jeweiligen Monaten für den referenzierten Kampagnentypen erwartet.</description>
    <fields>
        <fullName>MT_April__c</fullName>
        <label>April</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaignType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Kampagnentyp, für den die Werte erwartet werden.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Forecast Values</relationshipLabel>
        <relationshipName>Media_Forecast_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Forecast Value</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_ForecastVersion__c.object
<CustomObject>
    <description>Definiert einen Stand des Forecasting (z.B. für einen Monat).</description>
    <label>Media Forecast Version</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaForecastValueService_Test.cls
/************************************************************************************************************
Name:  		MT_MediaForecastValueService_Test
======================================================
Purpose: 	Test class for MT_MediaForecastValues, MT_MediaForecastValueService and MT_MediaForecastValueSelector
======================================================
History
-------
Date		AUTHOR						DETAIL
18.03.2017	Falco Aulitzky             Initial architecture & development
*************************************************************************************************************/

@isTest
private class MT_MediaForecastValueService_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_MediaForecastValues mfv = new MT_MediaForecastValues(new List<MT_ForecastValue__c>());
    Test.stopTest();
  }

  testmethod static void getMediaForecastValuesByIds() {
    MT_ForecastValue__c fv = [SELECT Id, MT_April__c FROM MT_ForecastValue__c limit 1];
    System.assertNotEquals(null, fv);

    Test.startTest();

    System.assert(!MT_MediaForecastValueService.getMediaForecastValuesByIds(new Set<Id>{
      fv.Id
    }).isEmpty());
    System.assert(MT_MediaForecastValueService.getMediaForecastValuesByIds(new Set<Id>()).isEmpty());
    System.assertEquals(1000, MT_MediaForecastValueService.getMediaForecastValuesByIds(new Set<Id>{
      fv.Id
    }).get(0).MT_April__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastValuesByIdsWithFields() {
    MT_ForecastValue__c fv = [SELECT Id, MT_April__c FROM MT_ForecastValue__c limit 1];
    System.assertNotEquals(null, fv);

    Test.startTest();

    System.assert(!MT_MediaForecastValueService.getMediaForecastValuesByIds(new Set<Id>{
      fv.Id
    }, new Set<String>{
      'Id'
    }).isEmpty());
    System.assert(MT_MediaForecastValueService.getMediaForecastValuesByIds(new Set<Id>(), new Set<String>{
      'Id'
    }).isEmpty());
    System.assertEquals(1000, MT_MediaForecastValueService.getMediaForecastValuesByIds(new Set<Id>{
      fv.Id
    }, new Set<String>{
      'MT_April__c'
    }).get(0).MT_April__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastValuesByMediaCampaignTypeIds() {
    MT_ForecastValue__c fv = [SELECT Id, MT_April__c FROM MT_ForecastValue__c limit 1];
    System.assertNotEquals(null, fv);

    MT_MediaCampaignType__c mct = [SELECT Id FROM MT_MediaCampaignType__c limit 1];
    System.assertNotEquals(null, mct);

    Test.startTest();

    System.assert(!MT_MediaForecastValueService.getMediaForecastValuesByMediaCampaignTypeIds(new Set<Id>{
      mct.Id
    }).isEmpty());
    System.assert(MT_MediaForecastValueService.getMediaForecastValuesByMediaCampaignTypeIds(new Set<Id>()).isEmpty());
    System.assertEquals(1000, MT_MediaForecastValueService.getMediaForecastValuesByMediaCampaignTypeIds(new Set<Id>{
      mct.Id
    }).get(0).MT_April__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastValuesByMediaCampaignTypeIdsWithFields() {
    MT_ForecastValue__c fv = [SELECT Id, MT_April__c FROM MT_ForecastValue__c limit 1];
    System.assertNotEquals(null, fv);

    MT_MediaCampaignType__c mct = [SELECT Id FROM MT_MediaCampaignType__c limit 1];
    System.assertNotEquals(null, mct);

    Test.startTest();

    System.assert(!MT_MediaForecastValueService.getMediaForecastValuesByMediaCampaignTypeIds(new Set<Id>{
      mct.Id
    }, new Set<String>{
      'Id'
    }).isEmpty());
    System.assert(MT_MediaForecastValueService.getMediaForecastValuesByMediaCampaignTypeIds(new Set<Id>(), new Set<String>{
      'Id'
    }).isEmpty());
    System.assertEquals(1000, MT_MediaForecastValueService.getMediaForecastValuesByMediaCampaignTypeIds(new Set<Id>{
      mct.Id
    }, new Set<String>{
      'MT_April__c'
    }).get(0).MT_April__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastValuesByForecastVersionIds() {
    MT_ForecastValue__c fv = [SELECT Id, MT_April__c FROM MT_ForecastValue__c limit 1];
    System.assertNotEquals(null, fv);

    MT_ForecastVersion__c fver = [SELECT Id FROM MT_ForecastVersion__c limit 1];
    System.assertNotEquals(null, fver);

    Test.startTest();

    System.assert(!MT_MediaForecastValueService.getMediaForecastValuesByForecastVersionIds(new Set<Id>{
      fver.Id
    }).isEmpty());
    System.assert(MT_MediaForecastValueService.getMediaForecastValuesByForecastVersionIds(new Set<Id>()).isEmpty());
    System.assertEquals(1000, MT_MediaForecastValueService.getMediaForecastValuesByForecastVersionIds(new Set<Id>{
      fver.Id
    }).get(0).MT_April__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastValuesByForecastVersionIdsWithFields() {
    MT_ForecastValue__c fv = [SELECT Id, MT_April__c FROM MT_ForecastValue__c limit 1];
    System.assertNotEquals(null, fv);

    MT_ForecastVersion__c fver = [SELECT Id FROM MT_ForecastVersion__c limit 1];
    System.assertNotEquals(null, fver);

    Test.startTest();

    System.assert(!MT_MediaForecastValueService.getMediaForecastValuesByForecastVersionIds(new Set<Id>{
      fver.Id
    }, new Set<String>{
      'Id'
    }).isEmpty());
    System.assert(MT_MediaForecastValueService.getMediaForecastValuesByForecastVersionIds(new Set<Id>(), new Set<String>{
      'Id'
    }).isEmpty());
    System.assertEquals(1000, MT_MediaForecastValueService.getMediaForecastValuesByForecastVersionIds(new Set<Id>{
      fver.Id
    }, new Set<String>{
      'MT_April__c'
    }).get(0).MT_April__c);

    Test.stopTest();
  }
}