src/objects/MT_ForecastVersion__c.object
<CustomObject>
    <description>Definiert einen Stand des Forecasting (z.B. für einen Monat).</description>
    <fields>
        <fullName>MT_VersionDate__c</fullName>
        <defaultValue>IF(MONTH(TODAY()) = 12, DATE(YEAR(TODAY()) + 1, 1, 1), DATE(YEAR(TODAY()), MONTH(TODAY()) + 1, 1))</defaultValue>
        <description>The month this forecast version applies to (e.g. creation month).</description>
        <label>Version Date</label>
        <type>Date</type>
    </fields>
    <label>Media Forecast Version</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MT_MediaForecastVersionSelector.cls
/************************************************************************************************************
Name:  		MT_MediaForecastVersionSelector
======================================================
Purpose: 	Selector class for MT_ForecastVersion__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
09.03.2017	Falco Aulitzky             Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaForecastVersionSelector extends MT_Selector {
  public static final String objectAPIName = MT_ForecastVersion__c.SobjectType.getDescribe().getName();

  public List<SObject> getRecordsOfYear(Integer wantedYear, Set<String> fields) {

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' WHERE MT_VersionDate__c <= ' + (wantedYear + 1) + '-01-01 AND MT_VersionDate__c >= ' + wantedYear + '-01-01 ORDER BY CreatedDate DESC NULLS FIRST';
    System.debug('Media Forecast Version: ' + query);
    return Database.query(query);
  }

  public List<SObject> getRecords(Set<String> fields) {
    Integer currentYear = System.Today().year();

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' WHERE MT_VersionDate__c <= ' + (currentYear + 1) + '-01-01 AND MT_VersionDate__c >= ' + currentYear + '-01-01 ORDER BY CreatedDate DESC NULLS FIRST';
    System.debug('Media Forecast Version: ' + query);
    return Database.query(query);
  }

  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    Integer currentYear = System.Today().year();

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' WHERE Id in ' + constructInClauseString(recordIds) + ' AND MT_VersionDate__c <= ' + (currentYear + 1) + '-01-01 AND MT_VersionDate__c >= ' + currentYear + '-01-01 ORDER BY CreatedDate DESC NULLS FIRST';
    System.debug('Media Forecast Version query by Ids: ' + query);
    return Database.query(query);
  }
}