src/objects/MT_ForecastValue__c.object
<CustomObject>
    <description>Speichert die erwarteten BMV- Werte, die ein Asset in den jeweiligen Monaten für den referenzierten Kampagnentypen erwartet.</description>
    <fields>
        <fullName>MT_MediaCampaignType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Kampagnentyp, für den die Werte erwartet werden.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Forecast Values</relationshipLabel>
        <relationshipName>Media_Forecast_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Forecast Value</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Typ dieser Kampagne. Steuert Konfigurationsparameter, z.B. Gewichtungsfaktoren, bei.</description>
        <label>Media Campaign Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4)) AND 5</booleanFilter>
            <errorMessage>Der ausgewählte Kampagnentyp ist inaktiv oder passt nicht zur Kampagne.</errorMessage>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <description>Das Asset, das diesen Kampagnentypen nutzt.</description>
        <label>Asset</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Media Campaign Types</relationshipLabel>
        <relationshipName>Media_Campaign_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Inaktive Typen können bei der Anlage von Kampagnen nicht mehr genutzt werden (Lookup- Filter)</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaignTypeSelector.cls
/**
 * It is a selector class for the MT_MediaCampaignType__c object
 *
 * History
 * -------
 * Date        AUTHOR                      DETAIL
 * 08.03.2017  Falco Aulitzky             Initial architecture & development
 * 20.04.2017  Faloc Aulitzky             Technical documentation
 */

/* Selector class to fetch data from the database */
public with sharing class MT_MediaCampaignTypeSelector extends MT_Selector {
  public static final String objectAPIName = MT_MediaCampaignType__c.SobjectType.getDescribe().getName();

  /*
  * Method to fetch data stored in salesforce
  * 
  * @param    Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type
  *           
  */
  public List<SObject> getRecords(Set<String> fields) {

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName;
    System.debug('Media Campaign Type query: ' + query);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  * 
  * @param    Set<Id>       recordIds is a set of MediaCampaignType ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type
  *
  */
  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' WHERE Id in ' + constructInClauseString(recordIds);
    System.debug('Media Campaign Type query by Ids: ' + query);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Boolean       boolean to determine if a record is active or not
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type
  *
  */
  public List<SObject> getRecordsByIsActive(Boolean isActive, Set<String> fields) {
    if (isActive == null) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' WHERE MT_IsActive__c = ' + isActive;
    System.debug('Media Campaign Type query by isActive: ' + query);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       assetIds is a set of Asset ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type
  *
  */
  public List<SObject> getRecordsByAssetIds(Set<Id> assetIds, Set<String> fields) {
    if (assetIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' WHERE MT_Asset_ref__c in ' + constructInClauseString(assetIds);
    System.debug('Media Campaign Type query by Asset ids: ' + query);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaCampaignType ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaForecastValue object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type with MediaForecastValues in it
  *
  */
  public List<SObject> getRecordsWithMediaForecastValuesByIds(Set<Id> recordIds, Set<String> mediaCampaignTypefields, Set<String> mediaForecastValueFields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(mediaCampaignTypefields) + ', (SELECT ' + constructFieldString(mediaForecastValueFields) + ' FROM Media_Forecast_Values__r) FROM ' + objectAPIName + ' WHERE Id in ' + constructInClauseString(recordIds);
    System.debug('Media Campaign Type with Media Forecast Values query by Ids: ' + query);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaCampaignType ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaTransparencyCampaign object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type with MediaTransparencyCampaign in it
  *
  */
  public List<SObject> getRecordsWithMediaTransparencyCampaignsByIds(Set<Id> recordIds, Set<String> mediaCampaignTypefields, Set<String> mediaCampaignFields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(mediaCampaignTypefields) + ',(SELECT ' + constructFieldString(mediaCampaignFields) + ' FROM Media_Campaigns__r) FROM ' + objectAPIName + ' WHERE Id in ' + constructInClauseString(recordIds);
    System.debug('Media Campaign Type with Media Transparency Campaigns query by Ids: ' + query);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaCampaignType ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaCampaignType object
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaForecastValue object
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaTransparencyCampaign object
  * @returns  List<SObject> a list of MediaCampaignType objects that are treated and stored as a generic type with MediaForecastValue and MediaTransparencyCampaign objects in it
  *
  */
  public List<SObject> getRecordsWithForecastValueAndMediaTransCampaignsByIds(Set<Id> recordIds, Set<String> mediaCampaignTypefields, Set<String> mediaForecastValueFields, Set<String> mediaFCampaignFields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(mediaCampaignTypefields) + ', (SELECT ' + constructFieldString(mediaForecastValueFields) + ' FROM Media_Forecast_Values__r), (SELECT ' + constructFieldString(mediaFCampaignFields) + ' FROM Media_Campaigns__r) FROM ' + objectAPIName + ' WHERE Id in ' + constructInClauseString(recordIds);
    System.debug('Media Campaign Type with Forecast Values and Media Campaigns query by Ids: ' + query);
    return Database.query(query);
  }
}