src/objects/MT_ForecastVersion__c.object
<CustomObject>
    <description>Definiert einen Stand des Forecasting (z.B. für einen Monat).</description>
    <fields>
        <fullName>MT_VersionName__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY())) &amp;&quot;_&quot;&amp; CASE(MONTH(TODAY())+1, 1, &quot;Januar&quot;, 2, &quot;Februar&quot;, 3, &quot;März&quot;,  4, &quot;April&quot;,  5, &quot;Mai&quot;,  6, &quot;Juni&quot;, 7, &quot;Juli&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;Oktober&quot;, 11, &quot;November&quot;, 12, &quot;Dezember&quot;, 13, &quot;Januar&quot;, &quot;None&quot;) &amp; &quot;_01&quot;</defaultValue>
        <description>Ein eindeutiger Name für diese Forecastingversion.</description>
        <label>Version Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Media Forecast Version</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MT_MediaForecastVersions.cls
/************************************************************************************************************
Name:  		MT_MediaForecastVersions
======================================================
Purpose: 	Domain class for MT_ForecastVersion__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
09.03.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaForecastVersions {
  private List<MT_ForecastVersion__c> scope;

  public MT_MediaForecastVersions(List<MT_ForecastVersion__c> scope) {
    this.scope = scope;
  }

  public static MT_ForecastVersion__c create(String name) {
    return new MT_ForecastVersion__c(
      MT_VersionName__c = name
    );

  }

  public class MT_MediaForecastVersionsException extends Exception {
  }
}