src/objects/MT_ForecastValue__c.object
<CustomObject>
    <description>Speichert die erwarteten BMV- Werte, die ein Asset in den jeweiligen Monaten für den referenzierten Kampagnentypen erwartet.</description>
    <fields>
        <fullName>MT_MediaCampaignType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Kampagnentyp, für den die Werte erwartet werden.</description>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Forecast Values</relationshipLabel>
        <relationshipName>Media_Forecast_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_MediaForecastVersion_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Stand des Forecasting, zu dem die Werte gelten.</description>
        <label>Media Forecast Version</label>
        <referenceTo>MT_ForecastVersion__c</referenceTo>
        <relationshipLabel>Media Forecast Values</relationshipLabel>
        <relationshipName>Media_Forecast_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Forecast Value</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_ForecastVersion__c.object
<CustomObject>
    <description>Definiert einen Stand des Forecasting (z.B. für einen Monat).</description>
    <label>Media Forecast Version</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaForecastValues.cls
/************************************************************************************************************
Name:  		MT_MediaForecastValues
======================================================
Purpose: 	Domain class for MT_ForecastValue__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
09.03.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaForecastValues {
  private List<MT_ForecastValue__c> scope;

  public MT_MediaForecastValues(List<MT_ForecastValue__c> scope) {
    this.scope = scope;
  }

  public static MT_ForecastValue__c create(MT_MediaCampaignType__c mediaCampaignType, MT_ForecastVersion__c mediaForecastVersion) {
    return new MT_ForecastValue__c(
      MT_MediaCampaignType__c = mediaCampaignType.Id,
      MT_MediaForecastVersion_ref__c = mediaForecastVersion.Id
    );

  }

  public class MT_MediaForecastValuesException extends Exception {
  }
}