src/objects/MT_ForecastVersion__c.object
<CustomObject>
    <description>Definiert einen Stand des Forecasting (z.B. für einen Monat).</description>
    <fields>
        <fullName>MT_Deadline__c</fullName>
        <defaultValue>IF(MONTH(TODAY()) &gt; 10, DATE(YEAR(TODAY()) + 1, MONTH(TODAY()) - 10, 5), DATE(YEAR(TODAY()), MONTH(TODAY()) + 2, 5))</defaultValue>
        <description>Definiert, bis wann die Business Units ihre Werte eintragen müssen. Danach darf nur noch das MSC die Werte bearbeiten.</description>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ist diese Checkbox aktiv, darf niemand mehr Werte zu diesem Forecasting eintragen.</description>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Forecast Version</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MT_ForecastVersion_TriggerHandler.cls
public with sharing class MT_ForecastVersion_TriggerHandler extends TriggerController {
  MT_ForecastVersion__c toBeLocked;

  public MT_ForecastVersion_TriggerHandler(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
    List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
    super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
  }

  public override void runAfterInsert() {
    List<MT_ForecastVersion__c> fv = ((List<MT_ForecastVersion__c>) lstNewItems);

    if (!Test.isRunningTest()) {
      toBeLocked = [SELECT Id, MT_IsLocked__c, MT_Deadline__c FROM MT_ForecastVersion__c WHERE Id != :fv.get(0).Id ORDER BY CreatedDate DESC NULLS LAST LIMIT 1];
    }

    if (toBeLocked != null && !toBeLocked.MT_IsLocked__c) {
      toBeLocked.MT_IsLocked__c = true;
      DateTime dt = ((List<MT_ForecastVersion__c>) lstNewItems).get(0).CreatedDate;
      toBeLocked.MT_Deadline__c = Date.newInstance(dT.year(), dT.month(), dT.day());
      update toBeLocked;

      Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
      req1.setComments('Automatic lock of previous record');
      req1.setObjectId(toBeLocked.Id);
      req1.setNextApproverIds(new List<Id>{
        UserInfo.getUserId()
      });
      Approval.ProcessResult result = Approval.process(req1);

      Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
      req2.setComments('Approving request.');
      req2.setAction('Approve');
      req2.setNextApproverIds(new Id[]{
        UserInfo.getUserId()
      });

      req2.setWorkitemId((result.getNewWorkitemIds()).get(0));

      Approval.ProcessResult result2 = Approval.process(req2);

      System.debug('#### Submit ' + result);
      System.debug('#### Approval ' + result2);
    }

    new MT_MediaForecastVersions((List<MT_ForecastVersion__c>) lstNewItems);

    System.debug('#### new AfterInsert ' + lstNewItems);
  }
}