src/objects/MT_ForecastVersion__c.object
<CustomObject>
    <description>Definiert einen Stand des Forecasting (z.B. für einen Monat).</description>
    <fields>
        <fullName>MT_VersionDate__c</fullName>
        <defaultValue>IF(MONTH(TODAY()) = 12, DATE(YEAR(TODAY()) + 1, 1, 1), DATE(YEAR(TODAY()), MONTH(TODAY()) + 1, 1))</defaultValue>
        <description>The month this forecast version applies to (e.g. creation month).</description>
        <label>Version Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_VersionName__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY())) &amp;&quot;_&quot;&amp; CASE(MONTH(TODAY())+1, 1, &quot;Januar&quot;, 2, &quot;Februar&quot;, 3, &quot;März&quot;,  4, &quot;April&quot;,  5, &quot;Mai&quot;,  6, &quot;Juni&quot;, 7, &quot;Juli&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;Oktober&quot;, 11, &quot;November&quot;, 12, &quot;Dezember&quot;, 13, &quot;Januar&quot;, &quot;None&quot;) &amp; &quot;_01&quot;</defaultValue>
        <description>Ein eindeutiger Name für diese Forecastingversion.</description>
        <label>Version Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Media Forecast Version</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MT_MediaForecastVersionService_Test.cls
/************************************************************************************************************
Name:  		MT_MediaForecastVersionService_Test
======================================================
Purpose: 	Test class for MT_MediaForecastVersions, MT_MediaForecastVersionService and MT_MediaForecastVersionSelector
======================================================
History
-------
Date		AUTHOR						DETAIL
18.03.2017	Falco Aulitzky             Initial architecture & development
*************************************************************************************************************/

@isTest
private class MT_MediaForecastVersionService_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_MediaForecastVersions mfv = new MT_MediaForecastVersions(new List<MT_ForecastVersion__c>());
    Test.stopTest();
  }

  testmethod static void getMediaForecastVersions() {

    Test.startTest();
    MT_ForecastVersion__c fver = MT_MediaForecastVersions.create('Test Version');
    insert fver;
    System.assert(!MT_MediaForecastVersionService.getMediaForecastVersions().isEmpty());
    System.assertEquals('Test Version', MT_MediaForecastVersionService.getMediaForecastVersions().get(0).MT_VersionName__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastVersionsWithFields() {

    Test.startTest();
    MT_ForecastVersion__c fv = MT_MediaForecastVersions.create('Test Version');
    insert fv;

    System.assert(!MT_MediaForecastVersionService.getMediaForecastVersions(new Set<String>{
      'Id'
    }).isEmpty());
    System.assertEquals('Test Version', MT_MediaForecastVersionService.getMediaForecastVersions(new Set<String>{
      'MT_VersionName__c'
    }).get(0).MT_VersionName__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastVersionsByIds() {

    Test.startTest();

    MT_ForecastVersion__c fv = MT_MediaForecastVersions.create('Test Version');
    insert fv;

    System.assert(!MT_MediaForecastVersionService.getMediaForecastVersionsByIds(new Set<Id>{
      fv.Id
    }).isEmpty());
    System.assert(MT_MediaForecastVersionService.getMediaForecastVersionsByIds(new Set<Id>()).isEmpty());
    System.assertEquals('Test Version', MT_MediaForecastVersionService.getMediaForecastVersionsByIds(new Set<Id>{
      fv.Id
    }).get(0).MT_VersionName__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastVersionsByIdsWithFields() {
    Test.startTest();

    MT_ForecastVersion__c fv = MT_MediaForecastVersions.create('Test Version');
    insert fv;

    System.assert(!MT_MediaForecastVersionService.getMediaForecastVersionsByIds(new Set<Id>{
      fv.Id
    }, new Set<String>{
      'Id'
    }).isEmpty());
    System.assert(MT_MediaForecastVersionService.getMediaForecastVersionsByIds(new Set<Id>(), new Set<String>{
      'Id'
    }).isEmpty());
    System.assertEquals('Test Version', MT_MediaForecastVersionService.getMediaForecastVersionsByIds(new Set<Id>{
      fv.Id
    }, new Set<String>{
      'MT_VersionName__c'
    }).get(0).MT_VersionName__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastVersionsForYear() {

    Test.startTest();

    MT_ForecastVersion__c fv = MT_MediaForecastVersions.create('Test Version');
    fv.MT_VersionDate__c = Date.newInstance(2017, 01, 01);
    insert fv;

    System.assert(!MT_MediaForecastVersionService.getMediaForecastVersionsForYear(2017).isEmpty());
    System.assert(MT_MediaForecastVersionService.getMediaForecastVersionsForYear(2000).isEmpty());
    System.assertEquals('Test Version', MT_MediaForecastVersionService.getMediaForecastVersionsForYear(2017).get(0).MT_VersionName__c);

    Test.stopTest();
  }

  testmethod static void getMediaForecastVersionsForYearWithFields() {
    Test.startTest();

    MT_ForecastVersion__c fv = MT_MediaForecastVersions.create('Test Version');
    fv.MT_VersionDate__c = Date.newInstance(2017, 01, 01);
    insert fv;

    System.assert(!MT_MediaForecastVersionService.getMediaForecastVersionsForYear(2017, new Set<String>{
      'Id'
    }).isEmpty());
    System.assert(MT_MediaForecastVersionService.getMediaForecastVersionsForYear(2000, new Set<String>{
      'Id'
    }).isEmpty());
    System.assertEquals('Test Version', MT_MediaForecastVersionService.getMediaForecastVersionsForYear(2017, new Set<String>{
      'MT_VersionName__c'
    }).get(0).MT_VersionName__c);

    Test.stopTest();
  }
}