src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <description>Das Asset, das diesen Kampagnentypen nutzt.</description>
        <label>Asset</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Media Campaign Types</relationshipLabel>
        <relationshipName>Media_Campaign_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Inaktive Typen können bei der Anlage von Kampagnen nicht mehr genutzt werden (Lookup- Filter)</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Asset__c.object
<CustomObject>
    <description>Wird benutzt, um die Marken (Assets) der Units zu pflegen.</description>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaignTypes.cls
/*****************************************************************************
Name:      MT_MediaCampaignTypes
======================================================
Purpose:   Domain class for MT_MediaCampaignType__c object
======================================================
History
-------
Date        AUTHOR                      DETAIL
08.02.2017  Duc Nguyen Tien             Initial architecture & development
*****************************************************************************/

public with sharing class MT_MediaCampaignTypes {
  private List<MT_MediaCampaignType__c > scope;
  private Map<Id, MT_MediaCampaignType__c> oldScopeMap;

  public MT_MediaCampaignTypes(List<MT_MediaCampaignType__c> scope) {
    this.scope = scope;
  }
  public MT_MediaCampaignTypes(List<MT_MediaCampaignType__c> scope, Map<Id, MT_MediaCampaignType__c> mOldScope) {
    this.scope = scope;
    this.oldScopeMap = mOldScope;
  }
  public static MT_MediaCampaignType__c create(String name, Boolean isActive, P7S1_Asset__c asset) {
    return new MT_MediaCampaignType__c(Name = name, MT_Asset_ref__c = asset.Id, MT_IsActive__c = isActive);
  }

}