src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_HasMediaDigital__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Aktiviert den Baustein Digital für diese Kampagne.</description>
        <label>Digital (71M)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_HasMediaDooH__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Aktiviert den Baustein DooH für diese Kampagne.</description>
        <label>DooH (7Screen)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_HasMediaTV__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Aktiviert den Baustein TV für diese Kampagne.</description>
        <label>TV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_Responsible_IM_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Der für diese Kampagne verantwortliche Benutzer von der IMA. Wird für Approval Prozesse und Benachrichtigungen im Flightplan verwendet.</description>
        <label>Internal Media Agency Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only users with the P7S1 Internal Agency role can be responsible internal media agents for a campaign.</errorMessage>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>P7S1_InternalAgency</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>MT_ResponsibleForMediaCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <description>Start des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_TvTarget__c.object
<CustomObject>
    <description>Enthält die prozentualen Verteilungen der TV- Ausstrahlungen auf Sender und Zeitschienen, die vertraglich vereinbart wurden. Initial gilt ein Mix für die gesamte Vertragslaufzeit, es kann aber zwischenzeitlich der Mix ab einem Stichmonat geändert werden. Im Reporting werden dann beide Mixe innerhalb ihrer jeweiligen Laufzeit mit den tatsächlichen Ausstrahlungen verglichen.</description>
    <label>TV Target</label>
    <nameField>
        <displayFormat>TVT-{000000}</displayFormat>
        <label>TV Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TV Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <description>Start der Laufzeit des Bausteins TV</description>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaignService_Test.cls
@isTest
private class MT_MediaCampaignService_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }
  testmethod static void getMediaCampaignsByIds() {
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    MT_MediaCampaign__c mc = [Select ID from MT_MediaCampaign__c limit 1];

    Test.startTest();

    system.assert(!MT_MediaCampaignService.getMediaCampaignsByIds(new Set<ID>{
      mc.Id
    }).isEmpty());
    system.assertEquals(mc.Id, MT_MediaCampaignService.getMediaCampaignsByIds(new Set<ID>{
      mc.Id
    }).get(0).Id);

    Test.stopTest();
  }
  testmethod static void getMediaCampaignsByIds_2() {
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    MT_MediaCampaign__c mc = [Select ID from MT_MediaCampaign__c limit 1];

    Test.startTest();

    system.assert(!MT_MediaCampaignService.getMediaCampaignsByIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'MT_RunTimeTVStart__c'
    }).isEmpty());
    system.assertEquals(Date.today().addMonths(-2), MT_MediaCampaignService.getMediaCampaignsByIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'MT_RunTimeTVStart__c'
    }).get(0).MT_RunTimeTVStart__c);

    Test.stopTest();
  }
  testmethod static void isMediaBuildingBlockStructureChanged() {
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    MT_MediaCampaign__c mc = [Select ID from MT_MediaCampaign__c limit 1];

    Test.startTest();

    system.assert(!new MT_MediaCampaignSelector().getRecordsByIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'MT_HasMediaDigital__c', 'MT_HasMediaDooH__c', 'MT_HasMediaTV__c'
    }).isEmpty());
    MT_MediaCampaign__c mcAssert = (MT_MediaCampaign__c) new MT_MediaCampaignSelector().getRecordsByIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'MT_HasMediaDigital__c', 'MT_HasMediaDooH__c', 'MT_HasMediaTV__c'
    }).get(0);
    system.assertEquals(false, mcAssert.MT_HasMediaDigital__c);
    system.assertEquals(false, mcAssert.MT_HasMediaDooH__c);
    system.assertEquals(true, mcAssert.MT_HasMediaTV__c);

    mcAssert.MT_HasMediaTV__c = false;

    Test.stopTest();
  }
  testmethod static void postFlightPlanUpdate() {
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    MT_MediaCampaign__c mc = [Select ID from MT_MediaCampaign__c limit 1];

    Test.startTest();

    MT_MediaCampaign__c mcAssert = (MT_MediaCampaign__c) new MT_MediaCampaignSelector().getRecordsByIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'MT_HasMediaDigital__c', 'MT_HasMediaDooH__c', 'MT_HasMediaTV__c'
    }).get(0);

    MT_MediaCampaignService.postFlightPlanUpdate(mcAssert, 'Test');

    Test.stopTest();
  }
  testmethod static void notifyImaAboutFlightPlanUpdate() {
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    MT_MediaCampaign__c mc = [Select ID from MT_MediaCampaign__c limit 1];

    Test.startTest();

    MT_MediaCampaign__c mcAssert = (MT_MediaCampaign__c) new MT_MediaCampaignSelector().getRecordsByIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name', 'MT_HasMediaDigital__c', 'MT_HasMediaDooH__c', 'MT_HasMediaTV__c'
    }).get(0);
    MT_TvTarget__c mbAssert = (MT_TvTarget__c) new MT_MediaBuildingBlockSelector().getRecordsByMediaCampaignIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name'
    }).get(0);
    mcAssert.MT_Responsible_IM_Agent__c = UserInfo.getUserId();
    MT_MediaCampaignService.notifyImaAboutFlightPlanUpdate(mcAssert, mbAssert.Id, 'Test');

    Test.stopTest();
  }
}