src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_Type__c</fullName>
        <description>Liefert den Namen des referenzierten Kampagnentypen, zur Vereinfachung der Einbindung (z.B. in Cockpit- Seiten, die nur die Kampagne laden).</description>
        <formula>MT_MediaCampaignType_ref__r.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_TvTarget__c.object
<CustomObject>
    <description>Enthält die prozentualen Verteilungen der TV- Ausstrahlungen auf Sender und Zeitschienen, die vertraglich vereinbart wurden. Initial gilt ein Mix für die gesamte Vertragslaufzeit, es kann aber zwischenzeitlich der Mix ab einem Stichmonat geändert werden. Im Reporting werden dann beide Mixe innerhalb ihrer jeweiligen Laufzeit mit den tatsächlichen Ausstrahlungen verglichen.</description>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Die Kampagne, zu der diese Zielvorgaben gehören.</description>
        <label>Media Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>TV Zielvorgaben</relationshipLabel>
        <relationshipName>TvTargets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <description>VERALTET: Wird nicht benötigt und kann gelöscht werden. Alle Abhängigkeiten zu diesem Feld brauchen die Unterscheidung nicht mehr, da das gesamte Objekt nur noch für TV gilt.

Alt:
Unterscheidet den Typ des Bausteins nach TV, Digital oder DooH.</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TV</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>DooH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TV Target</label>
    <nameField>
        <displayFormat>TVT-{000000}</displayFormat>
        <label>TV Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TV Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MT_MediaBuildingBlocks.cls
/************************************************************************************************************
Name:       MT_MediaBuildingBlocks
======================================================
Purpose:    Domain class for MT_TvTarget__c object
======================================================
History
-------
Date        AUTHOR                      DETAIL
17.11.2016  Duc Nguyen Tien             Initial architecture & development
23.01.2017  Duc Nguyen Tien             Update the media building block structure
*************************************************************************************************************/
public with sharing class MT_MediaBuildingBlocks {
  private List<MT_TvTarget__c> scope;

  public MT_MediaBuildingBlocks(List<MT_TvTarget__c> scope) {
    this.scope = scope;
  }

  public static MT_TvTarget__c create(MT_MediaCampaign__c mc, String type) {
    return new MT_TvTarget__c(
      MT_MediaCampaign_ref__c = mc.Id,
      MT_Type__c = type
    );
  }

  public class MT_MediaBuildingBlocksException extends Exception {
  }
}