src/objects/MT_MediaUpdateHistory__c.object
<CustomObject>
    <fields>
        <fullName>MT_ApprovalStatus__c</fullName>
        <description>Approval status of Opportunity Freigaben</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eingereicht</fullName>
                </value>
                <value>
                    <fullName>In Diskussion</fullName>
                </value>
                <value>
                    <fullName>Genehmigt</fullName>
                </value>
                <value>
                    <fullName>Abgelehnt</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MT_OpportunityApproval_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation to the Opportunity Approval to update</description>
        <label>Opportunity Approval</label>
        <referenceTo>P7S1_OpportunityApproval__c</referenceTo>
        <relationshipName>MT_UpdateRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Update History</label>
    <nameField>
        <displayFormat>UR{0000000}</displayFormat>
        <label>Update Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Update Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_MediaUpdateHistorySelector.cls
/************************************************************************************************************
Name:  		MT_MediaUpdateHistorySelector
======================================================
Purpose: 	Selector class for MT_MediaUpdateHistory__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
05.12.2016	Duc Nguyen Tien             Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaUpdateHistorySelector extends MT_Selector {
  public static final String objectAPIName = MT_MediaUpdateHistory__c.SobjectType.getDescribe().getName();
  public List<MT_MediaUpdateHistory__c> getApprovedRecordsByOpportunityApprovalRefId(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty())
      return new List<SObject>();
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_OpportunityApproval_ref__c in ' + constructInClauseString(recordIds) + ' and MT_ApprovalStatus__c =\'' + MT_Constants.getInstance().MediaUpdateHistory_Status_Approved + '\' order by CreatedDate desc';
    system.debug(query);
    return Database.query(query);
  }
  public List<MT_MediaUpdateHistory__c> getSubmittedRecordsByOpportunityApprovalRefId(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty())
      return new List<SObject>();
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_OpportunityApproval_ref__c in ' + constructInClauseString(recordIds) + ' and MT_ApprovalStatus__c =\'' + MT_Constants.getInstance().MediaUpdateHistory_Status_Submitted + '\' order by CreatedDate desc';
    system.debug(query);
    return Database.query(query);
  }
}