src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_OpportunityApproval_ref__c</fullName>
        <description>Die Referenz zur Opportunity Freigabe, muss mit der referenzierten Opportunity übereinstimmen.</description>
        <label>Opportunity Freigabe</label>
        <referenceTo>P7S1_OpportunityApproval__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Opportunity_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Die Opportunity, zu der die Kampagne gehört. Per Validierungsregel wird sichergestellt, dass die Opportunity und Opportunity Freigabe zueinander gehören. Aus der Opportunity werden weitere Informationen gezogen, der Zugriff wird mit der direkten Referenz vereinfacht.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <description>Liefert den Namen des referenzierten Kampagnentypen, zur Vereinfachung der Einbindung (z.B. in Cockpit- Seiten, die nur die Kampagne laden).</description>
        <formula>MT_MediaCampaignType_ref__r.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <description>Speichert die verschiedenen Typen der Kampagnen. Jedes Asset hat seine eigenen Typen und darf auch nur diese verwenden.</description>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <description>Das Asset, das diesen Kampagnentypen nutzt.</description>
        <label>Asset</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Media Campaign Types</relationshipLabel>
        <relationshipName>Media_Campaign_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Inaktive Typen können bei der Anlage von Kampagnen nicht mehr genutzt werden (Lookup- Filter)</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <description>Die Kategorie des Typs (intern / extern)</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <description>Zeigt den Status des zugehörigen Genehmigungsprozesses auf der Freigabe an</description>
        <inlineHelpText>Zeigt den Status des zugehörigen Genehmigungsprozesses auf der Freigabe an</inlineHelpText>
        <label>Genehmigungsstatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Asset__c.object
<CustomObject>
    <description>Wird benutzt, um die Marken (Assets) der Units zu pflegen.</description>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Die Referenz zum internen Partner. Ersetzt mittelfristig die Pickliste P7S1_internerPartner__c. Soll genutzt werden, um Sharing zu steuern, außerdem als Verbindungspunkt für Kampagnentypen und weitere Einflussfaktoren auf die Kampagnen.</description>
        <label>Interner Partner (Asset)</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>MT_OpportunityApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <label>Genehmigungsstatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eingereicht</fullName>
                </value>
                <value>
                    <fullName>In Diskussion</fullName>
                </value>
                <value>
                    <fullName>Genehmigt</fullName>
                </value>
                <value>
                    <fullName>Abgelehnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_internerPartner__c</fullName>
        <label>interner Partner</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>12Auto Group</fullName>
                </value>
                <value>
                    <fullName>7NXT</fullName>
                </value>
                <value>
                    <fullName>7Sports</fullName>
                </value>
                <value>
                    <fullName>Advopedia</fullName>
                </value>
                <value>
                    <fullName>Amorelie</fullName>
                </value>
                <value>
                    <fullName>Comvel</fullName>
                </value>
                <value>
                    <fullName>Discavo</fullName>
                </value>
                <value>
                    <fullName>etraveli</fullName>
                </value>
                <value>
                    <fullName>fem (sixx)</fullName>
                </value>
                <value>
                    <fullName>Flaconi</fullName>
                </value>
                <value>
                    <fullName>Gymondo</fullName>
                </value>
                <value>
                    <fullName>Magic Internet Holding</fullName>
                </value>
                <value>
                    <fullName>Marktguru</fullName>
                </value>
                <value>
                    <fullName>maxdome</fullName>
                </value>
                <value>
                    <fullName>moebel.de</fullName>
                </value>
                <value>
                    <fullName>mydays</fullName>
                </value>
                <value>
                    <fullName>P7S1 Digital</fullName>
                </value>
                <value>
                    <fullName>P7S1 Licensing</fullName>
                </value>
                <value>
                    <fullName>P7S1 PayTV</fullName>
                </value>
                <value>
                    <fullName>preis24.de</fullName>
                </value>
                <value>
                    <fullName>SilverTours</fullName>
                </value>
                <value>
                    <fullName>sonstiger</fullName>
                </value>
                <value>
                    <fullName>Starwatch</fullName>
                </value>
                <value>
                    <fullName>Studio 71</fullName>
                </value>
                <value>
                    <fullName>Stylight GmbH</fullName>
                </value>
                <value>
                    <fullName>tropo</fullName>
                </value>
                <value>
                    <fullName>TVRL</fullName>
                </value>
                <value>
                    <fullName>Valmano</fullName>
                </value>
                <value>
                    <fullName>Verivox</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_CreateMediaCampaignController.cls
/**
 * Handles the quick creation process for a media campaign, based on an opportunity approval
 */
public with sharing class MT_CreateMediaCampaignController {
  private final P7S1_OpportunityApproval__c oppApp;
  private final ApexPages.StandardController stdController;

  public MT_MediaCampaign__c campaign { get; set; }
  public List<MT_MediaCampaignType__c> campaignTypes { get; set; }
  public Boolean isExternalCampaign { get; set; }
  public Boolean isInternalCampaign { get; set; }

  public Boolean hasError { get; set; }
  public String errorMessage { get; set; }
  public String proceedTarget { get; set; }

  /**
   * Initialize this controller extension.
   */
  public MT_CreateMediaCampaignController(ApexPages.StandardController stdContr) {
    this.stdController = stdContr;

    Set<String> oppAppFields = MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.OppApp);
    oppAppFields.add('OwnerId');
    oppAppFields.add('P7S1_Opportunity__c');
    oppAppFields.add('P7S1_ApprovalState__c');
    oppAppFields.add('RecordTypeId');
    oppAppFields.add('RecordType.Name');
    oppAppFields.add('MT_Asset_ref__c');
    oppAppFields.add('P7S1_internerPartner__c');

    this.oppApp = (P7S1_OpportunityApproval__c) (new MT_OpportunityApprovalSelector()).getRecordsByIds(new Set<Id>{
      this.stdController.getId()
    }, oppAppFields).get(0);
  }

  /**
   * Prepare the campaign for the opportunity approval. If it already exists, jump directly to it.
   */
  public PageReference prepareCampaign() {
    if (this.oppApp == null) {
      this.setErrorMessage(MT_Labels.getInstance().ERR_MediaCampaign_No_OppApp);
      return null;
    }

    List<MT_MediaCampaign__c> existingCampaigns = [SELECT Id FROM MT_MediaCampaign__c WHERE MT_OpportunityApproval_ref__c = :this.oppApp.Id LIMIT 1];

    if (!existingCampaigns.isEmpty()) {
      this.proceedTarget = new ApexPages.StandardController(existingCampaigns[0]).view().getUrl();
      return null;
    }

    if (this.oppApp.RecordTypeId == null) {
      this.setErrorMessage(MT_Labels.getInstance().ERR_MediaCampaign_No_OppAppRecordTypeId);
      return null;
    }

    Map<String, Id> campaignCategoryTypes = getCategoryIds(MT_MediaCampaign__c.sObjectType.getDescribe().getName());
    Map<String, Id> oppAppCategoryTypes = getCategoryIds(P7S1_OpportunityApproval__c.sObjectType.getDescribe().getName());

    this.isExternalCampaign = this.oppApp.RecordTypeId == oppAppCategoryTypes.get('external');
    this.isInternalCampaign = this.oppApp.RecordTypeId == oppAppCategoryTypes.get('internal');

    if (!this.isExternalCampaign && !this.isInternalCampaign) {
      this.setErrorMessage(MT_Labels.getInstance().ERR_MediaCampaign_No_OppAppRecordTypeIdAllowed + ' (' + this.oppApp.RecordType.Name + ')');
      return null;
    }

    MT_Constants constants = MT_Constants.getInstance();

    if (oppApp.MT_Asset_ref__c != null) {
      this.campaignTypes = [SELECT ID, Name FROM MT_MediaCampaignType__c WHERE MT_IsActive__c = true AND MT_Type__c = :(this.isExternalCampaign ? constants.MediaCampaignType_External : constants.MediaCampaignType_Internal) AND MT_Asset_ref__c = :oppApp.MT_Asset_ref__c];
    } else {
      this.campaignTypes = [SELECT ID, Name FROM MT_MediaCampaignType__c WHERE MT_IsActive__c = true AND MT_Type__c = :(this.isExternalCampaign ? constants.MediaCampaignType_External : constants.MediaCampaignType_Internal) AND MT_Asset_ref__r.Name = :oppApp.P7S1_internerPartner__c];
    }

    this.campaign = new MT_MediaCampaign__c(
      RecordTypeId = this.isExternalCampaign ? campaignCategoryTypes.get('external') : campaignCategoryTypes.get('internal'),
      MT_Opportunity_ref__c = this.oppApp.P7S1_Opportunity__c,
      MT_OpportunityApproval_ref__c = this.oppApp.Id
    );

    MT_SynchronisationModule.synchronise(this.campaign, this.oppApp);

    Set<String> oppFields = MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.Opp);
    Opportunity opp = (Opportunity) (new MT_OpportunitySelector()).getRecordsByIds(new Set<Id>{
      this.oppApp.P7S1_Opportunity__c
    }, oppFields).get(0);

    MT_SynchronisationModule.synchronise(this.campaign, opp);

    return null;
  }

  /**
   * Store the campaign and redirect to it.
   */
  public PageReference createCampaign() {
    try {
      insert this.campaign;
    } catch (Exception e) {
      this.setErrorMessage(e.getMessage());
      return null;
    }

    ApexPages.StandardController ctrl = new ApexPages.StandardController(this.campaign);
    this.proceedTarget = ctrl.view().getUrl();
    return null;
  }

  /**
   * Return the record type ids for the given object, mapping them to external and internal campaigns.
   */
  private static Map<String, Id> getCategoryIds(String obj) {
    MT_Constants constants = MT_Constants.getInstance();

    List<RecordType> rts = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = :obj];

    Map<String, Id> result = new Map<String, Id>();

    for (RecordType rt : rts) {
      if (rt.DeveloperName.startsWith(constants.MediaCampaign_External_Prefix)) {
        if (result.containsKey('external')) {
          throw new MT_CreateMediaCampaignControllerException('The object ' + obj + ' contains multiple records types indicating an external campaign.');
        }

        result.put('external', rt.Id);
      } else if (rt.DeveloperName.startsWith(constants.MediaCampaign_Internal_Prefix)) {
        if (result.containsKey('internal')) {
          throw new MT_CreateMediaCampaignControllerException('The object ' + obj + ' contains multiple records types indicating an internal campaign.');
        }

        result.put('internal', rt.Id);
      }
    }

    if (result.size() != 2) {
      throw new MT_CreateMediaCampaignControllerException('The object ' + obj + ' does not contain exactly two record types for internal and external campaigns or these categories could not be mapped.');
    }

    return result;
  }

  private void setErrorMessage(String message) {
    this.hasError = true;
    this.errorMessage = message;

    if (this.oppApp == null) {
      PageReference proceedTo = new PageReference('/' + P7S1_OpportunityApproval__c.sObjectType.getDescribe().getKeyPrefix());
      this.proceedTarget = proceedTo.getUrl();
    } else {
      this.proceedTarget = '#close';
    }

  }

  /**
   * Used to indicate errors while processing.
   */
  public class MT_CreateMediaCampaignControllerException extends Exception {
  }
}