src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Monat(splan) gehört.</description>
        <label>Media Transparency Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>Media_Campaign_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <description>Der Monat, für den dieser Monatsplan gilt.</description>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaBuildingBlockMonthlyPlans.cls
/************************************************************************************************************
Name:       MT_MediaBuildingBlockMonthlyPlans
======================================================
Purpose:    Domain class for MT_MediaBuildingBlockMonthlyPlan__c object
======================================================
History
-------
Date        AUTHOR                      DETAIL
07.12.2016  Duc Nguyen Tien             Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaBuildingBlockMonthlyPlans {
  private List<MT_MediaCampaignMonthlyPlan__c> scope;

  public MT_MediaBuildingBlockMonthlyPlans(List<MT_MediaCampaignMonthlyPlan__c> scope) {
    this.scope = scope;
  }

  public static List<MT_MediaCampaignMonthlyPlan__c> createMonthlyPlans(MT_MediaCampaign__c mc, Date startDate, Date endDate) {
    List<MT_MediaCampaignMonthlyPlan__c> ret = new List<MT_MediaCampaignMonthlyPlan__c>();

    Date iteratorDate = Date.newInstance(startDate.year(), startDate.month(), 1);
    Date cacheEnd = Date.newInstance(endDate.year(), endDate.month(), 1);

    while (iteratorDate <= cacheEnd) {
      system.debug('iteratorDate: ' + iteratorDate + ' cacheEnd: ' + cacheEnd);

      ret.add(MT_MediaBuildingBlockMonthlyPlans.create(mc, iteratorDate));
      iteratorDate = iteratorDate.addMonths(1);
    }
    return ret;
  }
  public static MT_MediaCampaignMonthlyPlan__c create(MT_MediaCampaign__c mc, Date planningDate) {
    return new MT_MediaCampaignMonthlyPlan__c(
      MT_MediaCampaign_ref__c = mc.Id,
      MT_PlanningDate__c = planningDate
    );

  }
}