src/objects/MT_MediaBroadcastImportControlData__c.object
<CustomObject>
    <description>Media Broadcast Import Control Data object will have a single record summarizing the total number of records and their value totals for each of the data load by external integrating system</description>
    <fields>
        <fullName>Import_Date_Unique__c</fullName>
        <description>To maintain a single record per day</description>
        <label>Import Date Unique</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_ImportDate__c</fullName>
        <label>Import Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Broadcast Import Control Data</label>
    <nameField>
        <displayFormat>DIM-{0000000000}</displayFormat>
        <label>Data Import Thread ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Broadcast Import Control Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_MediaBIControlData_TriggerHandler.cls
/************************************************************************************************************
Name:  		MT_MediaBIControlData_TriggerHandler
======================================================
Purpose:
======================================================
History
-------
Date		AUTHOR						DETAIL
04.07.2017	Gokul-Prasad Palagiri		Initial Version MT-286
*************************************************************************************************************/
public class MT_MediaBIControlData_TriggerHandler extends TriggerController {
  public MT_MediaBIControlData_TriggerHandler(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
    List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
    super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
  }
  
  public override void runBeforeInsert() {
    
    for(MT_MediaBroadcastImportControlData__c controlRec : (List<MT_MediaBroadcastImportControlData__c>)lstNewItems){
        controlRec.Import_Date_Unique__c = String.valueOf(controlRec.MT_ImportDate__c) ;
    }

  }

  public override void runAfterInsert() {
  	
  	for (MT_MediaBroadcastImportControlData__c controlRec : (List<MT_MediaBroadcastImportControlData__c>) lstNewItems){
		Database.executeBatch(new MT_BroadcastImportDataValidator(controlRec));
	  }

  }


}