src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_KRSID__c</fullName>
        <description>Enthält die ID aus dem Altsystem (KRS), wird beim Import befüllt.</description>
        <externalId>true</externalId>
        <label>KRS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Monat(splan) gehört.</description>
        <label>Media Transparency Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Campaign Monthly Plans</relationshipLabel>
        <relationshipName>Media_Campaign_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <description>Der Monat, für den dieser Monatsplan gilt.</description>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign.</description>
    <fields>
        <fullName>MT_MediaBuildingBlockMonthlyPlan_ref__c</fullName>
        <description>Der Monat(splan), zu dem der Flight gehört.</description>
        <label>Media Campaign Monthly Plan</label>
        <referenceTo>MT_MediaCampaignMonthlyPlan__c</referenceTo>
        <relationshipLabel>Media Flights</relationshipLabel>
        <relationshipName>MediaFlights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Position__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The position of the flight in the list of all flights for a specific month.</description>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaBuildingBlockMonthlyPlanSelector.cls
/**
* Name:     MT_MediaBuildingBlockMonthlyPlanSelector
* Purpose:  Service class for MT_MediaBuildingBlockMonthlyPlan__c object
*
* History
* -------
* DATE        AUTHOR                      DETAIL
* 17.11.2016  Duc Nguyen Tien             Initial architecture and development
* 16.03.2017  Falco Aulitzky              Added missing functions
* 12.04.2017  Falco Aulitzky              Adding JavaDoc-Styled documentation
* 08.08.2017  GP                          Added getRecordsByKrsIds function
*/

/* Selector class to fetch data from the database */
public with sharing class MT_MediaBuildingBlockMonthlyPlanSelector extends MT_Selector {
  public static final String objectAPIName =  MT_MediaCampaignMonthlyPlan__c.SobjectType.getDescribe().getName();

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaBuildingBlockMonthlyPlan ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type
  *
  */
  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where Id in ' + constructInClauseString(recordIds);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaBuildingBlock ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type ordered by PlanningDate
  *
  */
  public List<SObject> getRecordsByParentIds(Set<Id> parentIds, Set<String> fields) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_MediaCampaign_ref__c in ' + constructInClauseString(parentIds) + ' order by MT_PlanningDate__c asc';
    return Database.query(query);
  }


  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaBuildingBlock ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaFlights object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type with MediaFlight objects matching MediaBuildingBlock ids ordered by PlanningDate
  *
  */
  public List<SObject> getRecordsWithMediaFlightsByParentIds(Set<Id> parentIds, Set<String> planningFields, Set<String> flightFieds) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(planningFields) + ', ( SELECT ' + constructFieldString(flightFieds) + ' FROM MediaFlights__r order by MT_Position__c asc) FROM ' + objectAPIName + ' where MT_MediaCampaign_ref__c in ' + constructInClauseString(parentIds) + ' order by MT_PlanningDate__c asc';
    return Database.query(query);
  }

 /*
  * Method to fetch data stored in salesforce
  *
  * @param    krsIds is a set of Strings that is used in where clause
  *           fields is a set of Strings that determines which fields are queried of the MT_MediaCampaignMonthlyPlan__c object
  * @returns  list of MT_MediaCampaignMonthlyPlan__c objects 
  *
  */
  public List<SObject> getRecordsByKrsIds(Set<String> krsIds, Set<String> fields) {
    if (krsIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where ' + MT_MediaCampaignMonthlyPlan__c.MT_MediaCampaign_ref__c.getDescribe().getRelationshipName() + '.' + MT_MediaCampaign__c.MT_KRSID__c.getDescribe().getName() +' in ' + constructInClauseString(krsIds) + ' order by '+ MT_MediaCampaignMonthlyPlan__c.MT_MediaCampaign_ref__c.getDescribe().getRelationshipName() + '.' + MT_MediaCampaign__c.MT_KRSID__c.getDescribe().getName() + ' asc';
    return Database.query(query);
  }
}