src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_ActualMonthlyBMV_sum__c</fullName>
        <description>Die Summe des über die Monat(splän)e ausgestrahlten Volumens.</description>
        <label>Sum of BMV Monthly Plan</label>
        <summarizedField>MT_MediaCampaignMonthlyPlan__c.MT_SumBMV__c</summarizedField>
        <summaryForeignKey>MT_MediaCampaignMonthlyPlan__c.MT_MediaCampaign_ref__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_KPI_Controller_Test.cls
@isTest
private class MT_KPI_Controller_Test {

  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_MediaCampaign__c camp = [SELECT ID, MT_ActualMonthlyBMV_sum__c FROM MT_MediaCampaign__c limit 1];

    MT_KPI_Controller ctlr = new MT_KPI_Controller(new ApexPages.StandardController(camp));

    Test.stopTest();

    System.assertNotEquals(null, ctlr.context);
    System.assertEquals(camp, ((MT_KPI_Controller.MT_KPI_Global_ConsoleComp) ctlr.context).mCamp);
  }
}