src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <description>Ende des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign.</description>
    <fields>
        <fullName>MT_BMVAmount__c</fullName>
        <description>Das Volumen dieses Flights, wird im Businessplan gepflegt.</description>
        <label>BMV Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_EndDate__c</fullName>
        <description>Enddatum dieses Flights, muss innerhalb des Monats(plans) liegen, dem der Flight zugeordnet ist, bzw. innerhalb der TV- und Vertragslaufzeit der Kampagne.</description>
        <label>To</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_MediaBuildingBlockMonthlyPlan_ref__c</fullName>
        <description>Der Monat(splan), zu dem der Flight gehört.</description>
        <label>Media Campaign Monthly Plan</label>
        <referenceTo>MT_MediaCampaignMonthlyPlan__c</referenceTo>
        <relationshipLabel>Media Flights</relationshipLabel>
        <relationshipName>MediaFlights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_StartDate__c</fullName>
        <description>Startdatum dieses Flights, muss innerhalb des Monats(plans) liegen, dem der Flight zugeordnet ist, bzw. innerhalb der TV- und Vertragslaufzeit der Kampagne.</description>
        <label>From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_TvTarget__c.object
<CustomObject>
    <description>Enthält die prozentualen Verteilungen der TV- Ausstrahlungen auf Sender und Zeitschienen, die vertraglich vereinbart wurden. Initial gilt ein Mix für die gesamte Vertragslaufzeit, es kann aber zwischenzeitlich der Mix ab einem Stichmonat geändert werden. Im Reporting werden dann beide Mixe innerhalb ihrer jeweiligen Laufzeit mit den tatsächlichen Ausstrahlungen verglichen.</description>
    <label>TV Target</label>
    <nameField>
        <displayFormat>TVT-{000000}</displayFormat>
        <label>TV Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TV Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MT_BusinessPlanningController_Test.cls
@isTest
private class MT_BusinessPlanningController_Test {

  @testSetup static void setup() {
    MT_Test.init();
  }
  testmethod static void constructor() {
    MT_MediaCampaign__c mc = [Select ID, MT_RunTimeTVEnd__c from MT_MediaCampaign__c limit 1];
    List<MT_TvTarget__c> mbbs = (List<MT_TvTarget__c>) new MT_MediaBuildingBlockSelector().getTVRecordsByMediaCampaignIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name'
    });
    system.assertEquals(1, mbbs.size(), 'Not found TV block for test');
    MT_BusinessPlanningController mCtrl = new MT_BusinessPLanningController(new ApexPages.StandardController(mbbs.get(0)));
  }
  testmethod static void getMediaBuildingBlock() {
    MT_MediaCampaign__c mc = [Select ID, MT_RunTimeTVEnd__c from MT_MediaCampaign__c limit 1];
    List<MT_TvTarget__c> mbbs = (List<MT_TvTarget__c>) new MT_MediaBuildingBlockSelector().getTVRecordsByMediaCampaignIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name'
    });
    system.assertEquals(1, mbbs.size(), 'Not found TV block for test');

    MT_BusinessPlanningController.MT_BusinessPlanningControllerDTO dto = MT_BusinessPlanningController.getMediaBuildingBlock(new List<Id>{
      mbbs.get(0).Id
    });
  }
  testmethod static void getMediaBuildingBlockMonthlyPlan() {
    MT_MediaCampaign__c mc = [Select ID, MT_RunTimeTVEnd__c from MT_MediaCampaign__c limit 1];
    List<MT_TvTarget__c> mbbs = (List<MT_TvTarget__c>) new MT_MediaBuildingBlockSelector().getTVRecordsByMediaCampaignIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name'
    });
    system.assertEquals(1, mbbs.size(), 'Not found TV block for test');
  }
  testmethod static void getMediaBuildingBlockMonthlyPlanWithMediaFlights() {
    MT_MediaCampaign__c mc = [Select ID, MT_RunTimeTVEnd__c from MT_MediaCampaign__c limit 1];
    List<MT_TvTarget__c> mbbs = (List<MT_TvTarget__c>) new MT_MediaBuildingBlockSelector().getTVRecordsByMediaCampaignIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name'
    });
    system.assertEquals(1, mbbs.size(), 'Not found TV block for test');

    MT_BusinessPlanningController.MT_BusinessPlanningControllerDTO dto = MT_BusinessPlanningController.getMediaBuildingBlockMonthlyPlanWithMediaFlights(new List<Id>{
      mbbs.get(0).Id
    });
  }
  testmethod static void upsertMediaBuildingBlockMonthlyPlansWithMediaFlights() {
    MT_MediaCampaign__c mc = [Select ID, MT_RunTimeTVEnd__c from MT_MediaCampaign__c limit 1];
    List<MT_TvTarget__c> mbbs = (List<MT_TvTarget__c>) new MT_MediaBuildingBlockSelector().getTVRecordsByMediaCampaignIds(new Set<ID>{
      mc.Id
    }, new Set<String>{
      'Name'
    });
    system.assertEquals(1, mbbs.size(), 'Not found TV block for test');

    MT_BusinessPlanningController.MT_BusinessPlanningControllerDTO dto = MT_BusinessPlanningController.getMediaBuildingBlockMonthlyPlanWithMediaFlights(new List<Id>{
      mbbs.get(0).Id
    });
    dto.monthlyPlanIdsToMediaFlights = new Map<Id, List<MT_MediaFlight__c>>();

    for (Id mdId : dto.mediaBuildingBlockMonthlyPlan.keySet()) {
      for (MT_MediaCampaignMonthlyPlan__c mmbbmp : dto.mediaBuildingBlockMonthlyPlan.get(mdId)) {
        dto.monthlyPlanIdsToMediaFlights.put(mmbbmp.Id, new List<MT_MediaFlight__c>{
          new MT_MediaFlight__c(MT_MediaBuildingBlockMonthlyPlan_ref__c = mmbbmp.Id, MT_BMVAmount__c = 1000, MT_StartDate__c = Date.today(), MT_EndDate__c = Date.today().addDays(1))
        });
      }
    }

    MT_BusinessPlanningController.MT_BusinessPlanningControllerDTO resp = MT_BusinessPlanningController.upsertMediaBuildingBlockMonthlyPlansWithMediaFlights(dto);
  }

  testmethod static void getObjectPermissions() {
    Map<String, MT_ObjectAccessDTO> perms = MT_BusinessPlanningController.getObjectPermissions();

    // make sure anything was returned
    System.assertNotEquals(null, perms);
    System.assert(!perms.isEmpty());

    // make sure the map contains the correct entries
    System.assertEquals(4, perms.size());

    System.assert(perms.containsKey('MT_MediaCampaign__c'));
    System.assert(perms.containsKey('MT_TvTarget__c'));
    System.assert(perms.containsKey('MT_MediaCampaignMonthlyPlan__c'));
    System.assert(perms.containsKey('MT_MediaFlight__c'));

    // make sure every of the entries contains also field information
    System.assertNotEquals(null, perms.get('MT_MediaCampaign__c'));
    System.assertNotEquals(null, perms.get('MT_MediaCampaign__c').fields);
    System.assert(!perms.get('MT_MediaCampaign__c').fields.isEmpty());

    System.assertNotEquals(null, perms.get('MT_TvTarget__c'));
    System.assertNotEquals(null, perms.get('MT_TvTarget__c').fields);
    System.assert(!perms.get('MT_TvTarget__c').fields.isEmpty());

    System.assertNotEquals(null, perms.get('MT_MediaCampaignMonthlyPlan__c'));
    System.assertNotEquals(null, perms.get('MT_MediaCampaignMonthlyPlan__c').fields);
    System.assert(!perms.get('MT_MediaCampaignMonthlyPlan__c').fields.isEmpty());

    System.assertNotEquals(null, perms.get('MT_MediaFlight__c'));
    System.assertNotEquals(null, perms.get('MT_MediaFlight__c').fields);
    System.assert(!perms.get('MT_MediaFlight__c').fields.isEmpty());
  }
}