src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign.</description>
    <fields>
        <fullName>MT_MediaBuildingBlockMonthlyPlan_ref__c</fullName>
        <description>Der Monat(splan), zu dem der Flight gehört.</description>
        <label>Media Campaign Monthly Plan</label>
        <referenceTo>MT_MediaCampaignMonthlyPlan__c</referenceTo>
        <relationshipLabel>Media Flights</relationshipLabel>
        <relationshipName>MediaFlights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Position__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The position of the flight in the list of all flights for a specific month.</description>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlightMotiveAllocation__c.object
<CustomObject>
    <description>Speichert die Zuordnung eines Motivs zu einem Flight und enthält zusätzliche, buchungsrelevante Informationen zur Ausstrahlung.</description>
    <fields>
        <fullName>MT_MediaFlight_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Flight, dem das Motiv zugeordnet wird.</description>
        <label>Media Flight</label>
        <referenceTo>MT_MediaFlight__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>MT_Media_Flight_Motive_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_Position__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Die Position des Motivs innerhalb des Flights.</description>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Flight Motive Allocation</label>
    <nameField>
        <displayFormat>MFMA-{00000}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Flight Motive Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaFlightSelector.cls
/************************************************************************************************************
Name:  		MT_MediaFlightSelector
======================================================
Purpose: 	Selector class for MT_MediaFlight__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
24.11.2016	Duc Nguyen Tien             Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaFlightSelector extends MT_Selector {

  public static final String objectAPIName = MT_MediaFlight__c.SobjectType.getDescribe().getName();

  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where Id in ' + constructInClauseString(recordIds);
    return Database.query(query);
  }

  public List<SObject> getRecordsByParentIds(Set<Id> parentIds, Set<String> fields) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_MediaBuildingBlockMonthlyPlan_ref__c in ' + constructInClauseString(parentIds);
    return Database.query(query);
  }

  public List<SObject> getRecordsWithMotiveAllocationsByParentIds(Set<Id> parentIds, Set<String> flightFields, Set<String> motiveFields) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(flightFields) + ', ( SELECT ' + constructFieldString(motiveFields) + ' FROM MT_Media_Flight_Motive_Allocations__r order by MT_Position__c asc) FROM ' + objectAPIName + ' where MT_MediaBuildingBlockMonthlyPlan_ref__c in ' + constructInClauseString(parentIds) + ' order by MT_Position__c asc';
    system.debug(query);
    return Database.query(query);
  }
}