src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_KRSID__c</fullName>
        <description>Enthält die ID aus dem Altsystem (KRS), wird beim Import befüllt.</description>
        <externalId>true</externalId>
        <label>KRS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Typ dieser Kampagne. Steuert Konfigurationsparameter, z.B. Gewichtungsfaktoren, bei.</description>
        <label>Media Campaign Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4)) AND 5</booleanFilter>
            <errorMessage>Der ausgewählte Kampagnentyp ist inaktiv oder passt nicht zur Kampagne.</errorMessage>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_OpportunityApproval_ref__c</fullName>
        <description>Die Referenz zur Opportunity Freigabe, muss mit der referenzierten Opportunity übereinstimmen.</description>
        <label>Opportunity Freigabe</label>
        <referenceTo>P7S1_OpportunityApproval__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Opportunity_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Die Opportunity, zu der die Kampagne gehört. Per Validierungsregel wird sichergestellt, dass die Opportunity und Opportunity Freigabe zueinander gehören. Aus der Opportunity werden weitere Informationen gezogen, der Zugriff wird mit der direkten Referenz vereinfacht.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaignSelector.cls
/*
* Name:  		MT_MediaBuildingBlockSelector
*
* Purpose: 	Selector class for MT_MediaCampaign__c object
*
* History
* -------
* Date	     	AUTHOR						DETAIL
* 17.11.2016	Duc Nguyen Tien             Initial architecture & development
* 21.04.2017    Falco Aulitzky              Javadoc style documentation added
*/
public with sharing class MT_MediaCampaignSelector extends MT_Selector {
  public static final String objectAPIName = MT_MediaCampaign__c.SobjectType.getDescribe().getName();

    /*
    * Method that queries data from the database
    *
    * @param     Set<Id> recordIds:  MediaTransparencyCampaign object ids
    *            Set<String> fields: fields that are queried on said object
    * @return generic list of an object
    */
  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where Id in ' + constructInClauseString(recordIds);
    system.debug(query);
    return Database.query(query);
  }

    /*
    * Method that queries data from the database
    *
    * @param     Set<Id> recordIds:  MediaCampaignType object ids
    *            Set<String> fields: fields that are queried on said object
    * @return generic list of an object
    */
  public List<SObject> getRecordsByMediaCampaignTypeIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_MediaCampaignType_ref__c in ' + constructInClauseString(recordIds);
    system.debug(query);
    return Database.query(query);
  }

    /*
    * Method that queries data from the database
    *
    * @param     Set<Id> recordIds:  OpporunityApproval object ids
    *            Set<String> fields: fields that are queried for MediaTransparencyCampaign objects
    * @return generic list of an object
    */
  public List<SObject> getRecordsByOpportunityApprovalIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_OpportunityApproval_ref__c in ' + constructInClauseString(recordIds);
    system.debug(query);
    return Database.query(query);
  }

    /*
    * Method that queries data from the database
    *
    * @param     Set<Id> recordIds:  Opporunity object ids
    *            Set<String> fields: fields that are queried for MediaTransparencyCampaign objects
    * @return generic list of an object
    */
  public List<SObject> getRecordsByOpportunityIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_Opportunity_ref__c in ' + constructInClauseString(recordIds);
    system.debug(query);
    return Database.query(query);
  }

  /**
   * Queries Media Campaigns by KRS IDs.
   *
   * @param krsIds set of KRS IDs
   * @param fields fields that are queried
   * @return query results
   */
  public List<sObject> getRecordsByKrsIds(Set<String> krsIds, Set<String> fields) {
    if (krsIds.isEmpty()) {
      return new List<sObject>();
    }

    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where ' + MT_MediaCampaign__c.MT_KRSID__c.getDescribe().getName() + ' in ' + constructInClauseString(krsIds);
    system.debug(query);
    return Database.query(query);
  }
}