src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_BmvTv__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Working value for the BMV (TV). Copied from the Opp Approval until approval is done, afterwards source of truth.</description>
        <label>BMV gesamt (TV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_HasMediaDigital__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Aktiviert den Baustein Digital für diese Kampagne.</description>
        <label>Digital (71M)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_HasMediaDooH__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Aktiviert den Baustein DooH für diese Kampagne.</description>
        <label>DooH (7Screen)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_HasMediaTV__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Aktiviert den Baustein TV für diese Kampagne.</description>
        <label>TV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_OpportunityApproval_ref__c</fullName>
        <description>Die Referenz zur Opportunity Freigabe, muss mit der referenzierten Opportunity übereinstimmen.</description>
        <label>Opportunity Freigabe</label>
        <referenceTo>P7S1_OpportunityApproval__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <description>Ende des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <description>Start des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_Status__c</fullName>
        <description>Der aktuelle Status der Kampagne (Entwurf, Freigegeben, Abgeschlossen, Abgebrochen)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planning final</fullName>
                </value>
                <value>
                    <fullName>Campaign approved</fullName>
                </value>
                <value>
                    <fullName>Campaign changed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Approvals</fullName>
                </value>
                <value>
                    <fullName>Contract signed</fullName>
                    <isActive>false</isActive>
                    <label>Contract signed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue1_RevenuePerUnit__c</fullName>
        <description>Der vereinbarte Umsatz pro Einheit für die Umsatzbeteiligungskomponente 1.</description>
        <label>Var. Umsatz 1 - Umsatz pro Einheit</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <description>Zeigt den Status des zugehörigen Genehmigungsprozesses auf der Freigabe an</description>
        <inlineHelpText>Zeigt den Status des zugehörigen Genehmigungsprozesses auf der Freigabe an</inlineHelpText>
        <label>Genehmigungsstatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <description>Das Ende der Laufzeit für den Baustein TV.</description>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <description>Start der Laufzeit des Bausteins TV</description>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_VariableRevenue1_RevenuePerUnit__c</fullName>
        <description>Der Umsatz je Einheit der variablen Umsatzbeteiligungskomponente 1.</description>
        <label>Var. Umsatz 1 - Umsatz pro Einheit</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <label>Genehmigungsstatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eingereicht</fullName>
                </value>
                <value>
                    <fullName>In Diskussion</fullName>
                </value>
                <value>
                    <fullName>Genehmigt</fullName>
                </value>
                <value>
                    <fullName>Abgelehnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_BmvTv__c</fullName>
        <inlineHelpText>Brutto Media Volumen TV Gesamt</inlineHelpText>
        <label>BMV gesamt (TV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P7S1_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaigns_Test.cls
@isTest
private class MT_MediaCampaigns_Test {

  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_MediaCampaigns cls = new MT_MediaCampaigns(new List<MT_MediaCampaign__c>());
    MT_MediaCampaigns cls2 = new MT_MediaCampaigns(new List<MT_MediaCampaign__c>(), new Map<Id, MT_MediaCampaign__c>());
    Test.stopTest();
  }

  @isTest static void approve() {
    Test.startTest();
    MT_MediaCampaign__c mc = MT_MediaCampaigns.approve(new MT_MediaCampaign__c());
    system.assertEquals(MT_Constants.getInstance().MediaCampaign_Status_Approved, mc.MT_Status__c);
    Test.stopTest();
  }

  @isTest static void reject() {
    Test.startTest();
    MT_MediaCampaign__c mc = MT_MediaCampaigns.reject(new MT_MediaCampaign__c());
    system.assertEquals(MT_Constants.getInstance().MediaCampaign_Status_Rejected, mc.MT_Status__c);
    Test.stopTest();
  }

  @isTest static void isInApprovedState() {
    Test.startTest();
    MT_MediaCampaign__c mc = new MT_MediaCampaign__c();

    Schema.DescribeFieldResult fieldResult = MT_MediaCampaign__c.MT_Status__c.getDescribe();
    List<Schema.PicklistEntry> ples = fieldResult.getPicklistValues();

    for (Schema.PicklistEntry ple : ples) {
      mc.MT_Status__c = ple.getValue();
      if (ple.getValue() == MT_Constants.getInstance().MediaCampaign_Status_Approved
        || ple.getValue() == MT_Constants.getInstance().MediaCampaign_Status_CampaignChanged
        || ple.getValue() == MT_Constants.getInstance().MediaCampaign_Status_InApprovals
        ) {
        system.assertEquals(true, MT_MediaCampaigns.isInApprovedState(mc));
      } else {
        system.assertEquals(false, MT_MediaCampaigns.isInApprovedState(mc));
      }
    }
    Test.stopTest();
  }

  @isTest static void isInApprovalProcess() {
    Test.startTest();
    MT_MediaCampaign__c mc = new MT_MediaCampaign__c();

    Schema.DescribeFieldResult fieldResult = MT_MediaCampaign__c.MT_Status__c.getDescribe();
    List<Schema.PicklistEntry> ples = fieldResult.getPicklistValues();

    for (Schema.PicklistEntry ple : ples) {
      mc.MT_Status__c = ple.getValue();
      if (ple.getValue() == MT_Constants.getInstance().MediaCampaign_Status_InApprovals) {
        system.assertEquals(true, MT_MediaCampaigns.isInApprovalProcess(mc));
      } else {
        system.assertEquals(false, MT_MediaCampaigns.isInApprovalProcess(mc));
      }
    }
    Test.stopTest();
  }

  @isTest static void FieldSync_LockValidation() {
    if (!MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.MC).contains('MT_RunTimeTVStart__c')) {
      system.assert(false, 'The tested field of MC is not in Synchronisation Module. Test method will not test the code properly!');
    }
    if (!MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.MC).contains('MT_RunTimeTVEnd__c')) {
      system.assert(false, 'The tested field of MC is not in Synchronisation Module. Test method will not test the code properly!');
    }

    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    Test.startTest();

    MT_MediaCampaign__c mc = [SELECT Id, MT_RunTimeTVStart__c, MT_RunTimeTVEnd__c, MT_Status__c FROM MT_MediaCampaign__c LIMIT 1];

    List<MT_MediaCampaign__c> newList = new List<MT_MediaCampaign__c>{
      mc
    };

    MT_MediaCampaign__c oldMC = mc.clone(true, true, true, true);

    Map<Id, MT_MediaCampaign__c> oldMap = new Map<Id, MT_MediaCampaign__c>{
      mc.Id => oldMC
    };

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_InApprovals;
    mc.MT_RunTimeTVStart__c = Date.today().addMonths(-3);
    mc.MT_RunTimeTVEnd__c = Date.today().addMonths(8);
    MT_MediaCampaigns mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampain_InApprovalLock);
      System.Assert(containsError, 'Error should be thrown but was not');
    }
    Test.stopTest();
  }

  @isTest static void testFieldSyncLockValidationForRejectedCampaign() {
    if (!MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.MC).contains('MT_RunTimeTVStart__c')) {
      system.assert(false, 'The tested field of MC is not in Synchronisation Module. Test method will not test the code properly!');
    }
    if (!MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.MC).contains('MT_RunTimeTVEnd__c')) {
      system.assert(false, 'The tested field of MC is not in Synchronisation Module. Test method will not test the code properly!');
    }

    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    oppApp.P7S1_ApprovalState__c = MT_Constants.getInstance().OpportunityApproval_ApprovalStatus_Rejected;
    update oppApp;

    Test.startTest();

    MT_MediaCampaign__c mc = [SELECT Id, MT_RunTimeTVStart__c, MT_RunTimeTVEnd__c, MT_Status__c FROM MT_MediaCampaign__c LIMIT 1];

    List<MT_MediaCampaign__c> newList = new List<MT_MediaCampaign__c>{
      mc
    };

    MT_MediaCampaign__c oldMC = mc.clone(true, true, true, true);

    Map<Id, MT_MediaCampaign__c> oldMap = new Map<Id, MT_MediaCampaign__c>{
      mc.Id => oldMC
    };

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_Draft;
    mc.MT_RunTimeTVStart__c = Date.today().addMonths(-5);
    mc.MT_RunTimeTVEnd__c = Date.today().addMonths(8);

    MT_MediaCampaigns mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampaign_Lock);
      System.assert(containsError, 'Error should be thrown but was not');
    }
    Test.stopTest();
  }

  @isTest static void assignOrCreateOpportunityApprovals_Case1() {
    //Testing the case where OppApp is not assigned explicitly, but Opp has OppApp assigned to it.
    Test.startTest();
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    P7S1_OpportunityApproval__c oppApp = [Select ID, P7S1_BmvTv__c from P7S1_OpportunityApproval__c where P7S1_Opportunity__c = :opp.Id limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, oppApp);

    MT_MediaCampaign__c assertMC = [Select ID, MT_OpportunityApproval_ref__c from MT_MediaCampaign__c];

    system.assertNotEquals(null, assertMC.MT_OpportunityApproval_ref__c, 'Opp App was not assigned');

    Test.stopTest();
  }

  @isTest static void assignOrCreateOpportunityApprovals_Case2() {
    //Testing the case where OppApp is not assigned explicitly and Opp has no OppApp assigned to it.
    Test.startTest();
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

    system.assertNotEquals(null, opp, 'Could not find proper opp for testing');

    MT_MediaCampaign__c assertMC = [Select ID, MT_OpportunityApproval_ref__c from MT_MediaCampaign__c];

    system.assertNotEquals(null, assertMC.MT_OpportunityApproval_ref__c);
    Test.stopTest();
  }

  @isTest static void testGetTargetFieldsAndGetDestFields() {
    Test.startTest();
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

    system.assertNotEquals(null, opp, 'Could not find proper opp for testing');

    MT_MediaCampaign__c assertMC = [Select ID, MT_OpportunityApproval_ref__c from MT_MediaCampaign__c];

    system.assertNotEquals(null, assertMC.MT_OpportunityApproval_ref__c);
    system.assertEquals(false, (MT_SynchronisationModule.getTargetFields(MT_SynchronisationModule.MC, MT_SynchronisationModule.Opp)).contains('MT_RunTimeTVEnd__c'));
    system.assertEquals(false, (MT_SynchronisationModule.getDestFields(MT_SynchronisationModule.Opp, MT_SynchronisationModule.MC)).contains('MT_RunTimeTVEnd__c'));

    Test.stopTest();
  }

  @isTest static void testAddErrorMethod() {
    if (!MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.MC).contains('MT_RunTimeTVStart__c')) {
      system.assert(false, 'The tested field of MC is not in Synchronisation Module. Test method will not test the code properly!');
    }
    if (!MT_SynchronisationModule.getSyncFields(MT_SynchronisationModule.MC).contains('MT_RunTimeTVEnd__c')) {
      system.assert(false, 'The tested field of MC is not in Synchronisation Module. Test method will not test the code properly!');
    }

    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    oppApp.P7S1_ApprovalState__c = MT_Constants.getInstance().OpportunityApproval_ApprovalStatus_Rejected;
    update oppApp;

    Test.startTest();

    MT_MediaCampaign__c mc = [Select ID, MT_OpportunityApproval_ref__c, MT_HasMediaDigital__c, MT_VariableRevenue1_RevenuePerUnit__c, MT_Status__c from MT_MediaCampaign__c];

    // changeing values
    List<MT_MediaCampaign__c> newList = new List<MT_MediaCampaign__c>{
      mc
    };

    MT_MediaCampaign__c oldMC = mc.clone(true, true, true, true);

    Map<Id, MT_MediaCampaign__c> oldMap = new Map<Id, MT_MediaCampaign__c>{
      mc.Id => oldMC
    };

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_Draft;
    mc.MT_HasMediaDigital__c = true;

    MT_MediaCampaigns mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampaign_Lock);
      System.assert(containsError, 'Error should be thrown but was not');
    }

    // new value
    newList.clear();
    newList.add(mc);

    oldMC = mc.clone(true, true, true, true);

    oldMap.clear();
    oldMap.put(mc.Id, oldMC);

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_Draft;
    mc.MT_HasMediaDooH__c = true;

    mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampaign_Lock);
      System.assert(containsError, 'Error should be thrown but was not');
    }

    // new value
    newList.clear();
    newList.add(mc);

    oldMC = mc.clone(true, true, true, true);

    oldMap.clear();
    oldMap.put(mc.Id, oldMC);

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_Draft;
    mc.MT_HasMediaTV__c = true;

    mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampaign_Lock);
      System.assert(containsError, 'Error should be thrown but was not');
    }

    // new value
    newList.clear();
    newList.add(mc);

    oldMC = mc.clone(true, true, true, true);

    oldMap.clear();
    oldMap.put(mc.Id, oldMC);

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_Draft;
    mc.MT_BmvTv__c = 1000;

    mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampaign_Lock);
      System.assert(containsError, 'Error should be thrown but was not');
    }

    // new value
    newList.clear();
    newList.add(mc);

    oldMC = mc.clone(true, true, true, true);

    oldMap.clear();
    oldMap.put(mc.Id, oldMC);

    mc.MT_Status__c = MT_Constants.getInstance().MediaCampaign_Status_Draft;
    mc.MT_VariableRevenue1_RevenuePerUnit__c = 1000;

    mcDomain = new MT_MediaCampaigns(newList, oldMap);

    try {
      mcDomain.FieldSync_LockValidation();
      System.assert(false, 'Field sync lock should have triggered an error.');
    } catch (Exception e) {
      Boolean containsError = e.getMessage().contains(MT_Labels.getInstance().ERR_Sync_MediaCampaign_Lock);
      System.assert(containsError, 'Error should be thrown but was not');
    }

    Test.stopTest();
  }

  @IsTest
  private static void testGetRecordTypeIdForInternalCampaign() {
    Test.startTest();
    Id recTypeId = MT_MediaCampaigns.getRecordTypeIdForInternalCampaign();
    Test.stopTest();

    System.assertNotEquals(null, recTypeId, 'Record type ID was not retrieved');
  }

  @IsTest
  private static void testGetRecordTypeIdForExternalCampaign() {
    Test.startTest();
    Id recTypeId = MT_MediaCampaigns.getRecordTypeIdForExternalCampaign();
    Test.stopTest();

    System.assertNotEquals(null, recTypeId, 'Record type ID was not retrieved');
  }
}