src/objects/MT_MediaCampaignMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume for a campaign</description>
    <label>Media Campaign Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Campaign Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign.</description>
    <fields>
        <fullName>MT_EndDate__c</fullName>
        <description>Enddatum dieses Flights, muss innerhalb des Monats(plans) liegen, dem der Flight zugeordnet ist, bzw. innerhalb der TV- und Vertragslaufzeit der Kampagne.</description>
        <label>To</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_MediaBuildingBlockMonthlyPlan_ref__c</fullName>
        <description>Der Monat(splan), zu dem der Flight gehört.</description>
        <label>Media Campaign Monthly Plan</label>
        <referenceTo>MT_MediaCampaignMonthlyPlan__c</referenceTo>
        <relationshipLabel>Media Flights</relationshipLabel>
        <relationshipName>MediaFlights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_StartDate__c</fullName>
        <description>Startdatum dieses Flights, muss innerhalb des Monats(plans) liegen, dem der Flight zugeordnet ist, bzw. innerhalb der TV- und Vertragslaufzeit der Kampagne.</description>
        <label>From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaFlights.cls
/************************************************************************************************************
Name:      MT_MediaFlights
======================================================
Purpose:   Domain class for MT_MediaFlight__c object
======================================================
History
-------
Date    AUTHOR            DETAIL
16.03.2017  Falco Aulitzky              Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaFlights {
  private List<MT_MediaFlight__c> scope;

  public MT_MediaFlights(List<MT_MediaFlight__c> scope) {
    this.scope = scope;
  }

  public static MT_MediaFlight__c create(Date startDate, Date endDate, MT_MediaCampaignMonthlyPlan__c buildingBlock) {
    return new MT_MediaFlight__c(
      MT_StartDate__c = startDate,
      MT_EndDate__c = endDate,
      MT_MediaBuildingBlockMonthlyPlan_ref__c = buildingBlock.Id
    );
  }

  public class MT_MediaFlightsException extends Exception {
  }
}