src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_ActualMonthlyBMV_sum__c</fullName>
        <description>Die Summe des über die Monat(splän)e ausgestrahlten Volumens.</description>
        <label>Sum of BMV Monthly Plan</label>
        <summarizedField>MT_MediaCampaignMonthlyPlan__c.MT_SumBMV__c</summarizedField>
        <summaryForeignKey>MT_MediaCampaignMonthlyPlan__c.MT_MediaCampaign_ref__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MT_BmvTv__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Working value for the BMV (TV). Copied from the Opp Approval until approval is done, afterwards source of truth.</description>
        <label>BMV gesamt (TV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_KPI_Controller.cls
/************************************************************************************************************
Name:       MT_KPI_Controller
======================================================
Purpose:    Controller for all MT_KPI vf pages
======================================================
History
-------
Date        AUTHOR                      DETAIL
19.01.2017  Duc Nguyen Tien             Initial architecture & development
15.02.2017  Falco Aulitzky              Updated tvBlock and istBlock to finalize the functionality
*************************************************************************************************************/
public with sharing class MT_KPI_Controller {

  private final sObject mysObject;
  private Schema.SObjectType objType;
  public ContextObjectWrapper context { get; set; }

  public MT_KPI_Controller(ApexPages.StandardController stdController) {
    this.mysObject = (sObject) stdController.getRecord();
    this.objType = this.mysObject.getSobjectType();

    if (this.objType == MT_MediaCampaign__c.SobjectType) {
      context = new MT_KPI_Global_ConsoleComp(this.mysObject);
    }
  }

  public void init(Schema.SobjectType objType) {
  }

  public abstract class ContextObjectWrapper {
    public Map<String, Object> var { get; set; }
    abstract void init();
  }

  public class MT_KPI_Global_ConsoleComp extends ContextObjectWrapper {
    public MT_MediaCampaign__c mCamp;

    public MT_KPI_Global_ConsoleComp(Sobject obj) {
      this.mCamp = (MT_MediaCampaign__c) obj;

      var = new Map<String, Object>();

      init();
    }

    public override void init() {
      calculatedProgressBar();
    }

    public void calculatedProgressBar() {
      Double d = Math.min(this.mCamp.MT_ActualMonthlyBMV_sum__c == 0 ? 0 : this.mCamp.MT_ActualMonthlyBMV_sum__c / this.mCamp.MT_BMVTv__c, 1);
      var.put('progressBarPercentage', d * 100);
    }
  }
}