src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_ProSaOrder__c.object
<CustomObject>
    <description>Dokumentiert einen Auftrag, der in ProSa angelegt wurde, zur Zuordnung der Ausstrahlungsdaten zu einer Kampagne.</description>
    <fields>
        <fullName>MT_OrderNumber__c</fullName>
        <description>Die Nummer, ProSa vergeben hat.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ProSa Order</label>
    <nameField>
        <label>ProSa Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProSa Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_ProSaOrderService_Test.cls
/************************************************************************************************************
Name:  		MT_ProSaOrderService_Test
======================================================
Purpose: 	Test class for MT_ProSaOrders, MT_ProSaOrderService and MT_ProSaOrderSelector
======================================================
History
-------
Date		AUTHOR						DETAIL
15.03.2017	Falco Aulitzky             Initial architecture & development
*************************************************************************************************************/

@isTest
private class MT_ProSaOrderService_Test {
  @testSetup static void setup() {
    MT_Test.init();

    Account acc = [Select Id FROM Account limit 1];
    System.assertNotEquals(null, acc);

    Opportunity opp = [Select Id FROM Opportunity limit 1];
    System.assertNotEquals(null, opp);

    P7S1_OpportunityApproval__c oppApp = [Select Id FROM P7S1_OpportunityApproval__c limit 1];
    System.assertNotEquals(null, oppApp);
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_ProSaOrders amp = new MT_ProSaOrders(new List<MT_ProSaOrder__c>());
    Test.stopTest();
  }

  testmethod static void getProSaOrdersByMediaCampaignIds() {
    MT_MediaCampaign__c mc = [SELECT Id FROM MT_MediaCampaign__c limit 1];
    System.assertNotEquals(null, mc);

    MT_ProSaOrder__c pso = [SELECT Id FROM MT_ProSaOrder__c limit 1];
    System.assertNotEquals(null, pso);

    Test.startTest();

    System.assert(!MT_ProSaOrderService.getProSaOrdersByMediaCampaignIds(new Set<Id>{
      mc.Id
    }).isEmpty());
    System.assert(MT_ProSaOrderService.getProSaOrdersByMediaCampaignIds(new Set<Id>()).isEmpty());
    System.assertEquals('123334', MT_ProSaOrderService.getProSaOrdersByMediaCampaignIds(new Set<Id>{
      mc.Id
    }).get(0).MT_OrderNumber__c);

    Test.stopTest();
  }

  testmethod static void getProSaOrdersByMediaCampaignIdsWithFields() {
    MT_MediaCampaign__c mc = [SELECT Id FROM MT_MediaCampaign__c limit 1];
    System.assertNotEquals(null, mc);

    MT_ProSaOrder__c pso = [SELECT Id FROM MT_ProSaOrder__c limit 1];
    System.assertNotEquals(null, pso);

    Test.startTest();

    System.assert(!MT_ProSaOrderService.getProSaOrdersByMediaCampaignIds(new Set<Id>{
      mc.Id
    }, new Set<String>{
      'MT_OrderNumber__c'
    }).isEmpty());
    System.assert(MT_ProSaOrderService.getProSaOrdersByMediaCampaignIds(new Set<Id>(), new Set<String>{
      'MT_OrderNumber__c'
    }).isEmpty());
    System.assertEquals('123334', MT_ProSaOrderService.getProSaOrdersByMediaCampaignIds(new Set<Id>{
      mc.Id
    }, new Set<String>{
      'MT_OrderNumber__c'
    }).get(0).MT_OrderNumber__c);

    Test.stopTest();
  }
}