src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_ProSaOrder__c.object
<CustomObject>
    <description>Dokumentiert einen Auftrag, der in ProSa angelegt wurde, zur Zuordnung der Ausstrahlungsdaten zu einer Kampagne.</description>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <description>Die Kampagne, zu der der Auftrag gehört.</description>
        <label>Media Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>ProSa Orders</relationshipLabel>
        <relationshipName>ProSa_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>MT_OrderNumber__c</fullName>
        <description>Die Nummer, ProSa vergeben hat.</description>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ProSa Order</label>
    <nameField>
        <label>ProSa Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProSa Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_ProSaOrders.cls
/************************************************************************************************************
Name:  		MT_ProSaOrders
======================================================
Purpose: 	Domain class for MT_ProSaOrder__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
15.03.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_ProSaOrders {
  private List<MT_ProSaOrder__c> scope;

  public MT_ProSaOrders(List<MT_ProSaOrder__c> scope) {
    this.scope = scope;
  }

  public static MT_ProSaOrder__c create(MT_MediaCampaign__c mediaCampaign, String orderNumber) {
    return new MT_ProSaOrder__c(
      MT_MediaCampaign_ref__c = mediaCampaign.Id,
      MT_OrderNumber__c = orderNumber);
  }

  public class MT_ProSaOrdersException extends Exception {
  }
}