src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <description>Ende des Ausstrahlungszeitraums für den TV- Baustein.</description>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <description>Zeigt den Status des zugehörigen Genehmigungsprozesses auf der Freigabe an</description>
        <inlineHelpText>Zeigt den Status des zugehörigen Genehmigungsprozesses auf der Freigabe an</inlineHelpText>
        <label>Genehmigungsstatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <description>Das Ende der Laufzeit für den Baustein TV.</description>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <label>Genehmigungsstatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eingereicht</fullName>
                </value>
                <value>
                    <fullName>In Diskussion</fullName>
                </value>
                <value>
                    <fullName>Genehmigt</fullName>
                </value>
                <value>
                    <fullName>Abgelehnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_ApprovalHistoryController_Test.cls
@isTest
private class MT_ApprovalHistoryController_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }

  testmethod static void constructor() {
    Opportunity opp = [Select Id from Opportunity limit 1]; // If no opp is returned it will throw an error. testSetup method must be adjusted
    P7S1_OpportunityApproval__c oppApp = [Select ID from P7S1_OpportunityApproval__c limit 1]; // If no oppApp is returned it will throw an error. testSetup method must be adjusted
    system.assertNotEquals(null, opp);
    system.assertNotEquals(null, oppApp);

    Test.startTest();

    oppApp.P7S1_ApprovalState__c = MT_Constants.getInstance().OpportunityApproval_ApprovalStatus_Submitted;
    update oppApp;

    oppApp.P7S1_ApprovalState__c = MT_Constants.getInstance().OpportunityApproval_ApprovalStatus_Approved;
    update oppApp;

    MT_MediaCampaign__c mc = [Select ID, MT_RunTimeTVEnd__c from MT_MediaCampaign__c limit 1];

    mc.MT_RunTimeTVEnd__c = mc.MT_RunTimeTVEnd__c.addMonths(2);
    update mc;
    system.debug('Approval Process Module start');
    MT_ApprovalProcessModule.startApprovalProcess(oppApp.Id, mc.Id);

    MT_ApprovalHistoryController ctrl = new MT_ApprovalHistoryController(new ApexPages.StandardController(oppApp));

    Test.stopTest();
  }
}