src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign.</description>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlightMotiveAllocation__c.object
<CustomObject>
    <description>Speichert die Zuordnung eines Motivs zu einem Flight und enthält zusätzliche, buchungsrelevante Informationen zur Ausstrahlung.</description>
    <fields>
        <fullName>MT_MediaFlight_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Flight, dem das Motiv zugeordnet wird.</description>
        <label>Media Flight</label>
        <referenceTo>MT_MediaFlight__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>MT_Media_Flight_Motive_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Flight Motive Allocation</label>
    <nameField>
        <displayFormat>MFMA-{00000}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Flight Motive Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaFlightMotiveAllocService_Test.cls
/************************************************************************************************************
Name:  		MT_MediaFlightMotiveAllocService_Test
======================================================
Purpose: 	Test class for MT_MediaFlightMotiveAllocations, MT_MediaFlightMotiveAllocationService and MT_MediaFlightMotiveAllocationSelector
======================================================
History
-------
Date		AUTHOR						DETAIL
16.03.2017	Falco Aulitzky             Initial architecture & development
*************************************************************************************************************/

@isTest
private class MT_MediaFlightMotiveAllocService_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    Test.startTest();
    MT_MediaFlightMotiveAllocations amp = new MT_MediaFlightMotiveAllocations(new List<MT_MediaFlightMotiveAllocation__c>());
    Test.stopTest();
  }

  testmethod static void getMediaFlightMotiveAllocationsByParentIds() {
    MT_MediaFlight__c mf = [SELECT Id FROM MT_MediaFlight__c limit 1];
    System.assertNotEquals(null, mf);

    Test.startTest();

    System.assert(!MT_MediaFlightMotiveAllocationService.getMediaFlightMotiveAllocationsByParentIds(new Set<Id>{
      mf.Id
    }).isEmpty());
    System.assert(MT_MediaFlightMotiveAllocationService.getMediaFlightMotiveAllocationsByParentIds(new Set<Id>()).isEmpty());
    System.assertEquals(mf.Id, MT_MediaFlightMotiveAllocationService.getMediaFlightMotiveAllocationsByParentIds(new Set<Id>{
      mf.Id
    }).get(0).MT_MediaFlight_ref__c);

    Test.stopTest();
  }

  testmethod static void getMediaFlightMotiveAllocationsByIds() {
    MT_MediaFlight__c mf = [SELECT Id FROM MT_MediaFlight__c limit 1];
    System.assertNotEquals(null, mf);

    MT_MediaFlightMotiveAllocation__c mfma = [SELECT Id FROM MT_MediaFlightMotiveAllocation__c limit 1];
    System.assertNotEquals(null, mfma);

    Test.startTest();

    System.assert(!MT_MediaFlightMotiveAllocationService.getMediaFlightMotiveAllocationsByIds(new Set<Id>{
      mfma.Id
    }).isEmpty());
    System.assert(MT_MediaFlightMotiveAllocationService.getMediaFlightMotiveAllocationsByIds(new Set<Id>()).isEmpty());
    System.assertEquals(mf.Id, MT_MediaFlightMotiveAllocationService.getMediaFlightMotiveAllocationsByIds(new Set<Id>{
      mfma.Id
    }).get(0).MT_MediaFlight_ref__c);

    Test.stopTest();
  }
}