src/objects/MT_MediaFlightMotiveAllocation__c.object
<CustomObject>
    <description>Speichert die Zuordnung eines Motivs zu einem Flight und enthält zusätzliche, buchungsrelevante Informationen zur Ausstrahlung.</description>
    <fields>
        <fullName>MT_MediaFlight_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Flight, dem das Motiv zugeordnet wird.</description>
        <label>Media Flight</label>
        <referenceTo>MT_MediaFlight__c</referenceTo>
        <relationshipLabel>Media Flight Motive Allocations</relationshipLabel>
        <relationshipName>MT_Media_Flight_Motive_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_Position__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Die Position des Motivs innerhalb des Flights.</description>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Flight Motive Allocation</label>
    <nameField>
        <displayFormat>MFMA-{00000}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Flight Motive Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaFlightMotiveAllocationSelector.cls
/************************************************************************************************************
Name:  		MT_MediaFlightMotiveAllocationSelector
======================================================
Purpose: 	Selector class for MT_MediaFlightMotiveAllocation__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
06.02.2017	Duc Nguyen Tien             Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_MediaFlightMotiveAllocationSelector extends MT_Selector {
  public static final String objectAPIName = MT_MediaFlightMotiveAllocation__c.SobjectType.getDescribe().getName();

  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty())
      return new List<SObject>();
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where Id in ' + constructInClauseString(recordIds) + ' order by MT_Position__c desc';
    return Database.query(query);
  }
  public List<SObject> getRecordsByMediaFlightsIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty())
      return new List<SObject>();
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_MediaFlight_ref__c in ' + constructInClauseString(recordIds) + ' order by MT_Position__c desc';
    return Database.query(query);
  }

}