src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_KRSID__c</fullName>
        <description>Enthält die ID aus dem Altsystem (KRS), wird beim Import befüllt.</description>
        <externalId>true</externalId>
        <label>KRS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_MediaCampaignType_ref__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Der Typ dieser Kampagne. Steuert Konfigurationsparameter, z.B. Gewichtungsfaktoren, bei.</description>
        <label>Media Campaign Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4)) AND 5</booleanFilter>
            <errorMessage>Der ausgewählte Kampagnentyp ist inaktiv oder passt nicht zur Kampagne.</errorMessage>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Media Campaign</value>
            </filterItems>
            <filterItems>
                <field>MT_MediaCampaignType__c.MT_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaCampaignSelector_Test.cls
/**
 * Unit test for <code>MT_MediaCampaignSelector</code> class.
 *
 * @author Fabio Andree Scheurel (MaibornWolff GmbH)
 */
@IsTest
private class MT_MediaCampaignSelector_Test {

  @IsTest
  private static void testGetRecordsByKrsIdsWithEmptySet() {
    Test.startTest();
    List<SObject> result = new MT_MediaCampaignSelector().getRecordsByKrsIds(new Set<String>(), new Set<String>());
    Test.stopTest();

    System.assertNotEquals(null, result, 'A null result was returned');
    System.assertEquals(0, result.size(), 'An other number of records was returned than should be.');
  }

  @IsTest
  private static void testGetRecordsByKrsIds() {
    MT_Test.Init();

    Set<String> krsIds = new Set<String>();

    List<MT_MediaCampaign__c> campaigns = [SELECT MT_KRSID__c
                                            FROM MT_MediaCampaign__c];
    for (Integer i = 0; i < campaigns.size(); i++) {
      MT_MediaCampaign__c campaign = campaigns.get(i);
      campaign.MT_KRSID__c = 'testAAA#' + i;
      krsIds.add(campaign.MT_KRSID__c);
    }
    update campaigns;

    Set<String> fields = new Set<String> {
      MT_MediaCampaign__c.Id.getDescribe().getName(),
      MT_MediaCampaign__c.Name.getDescribe().getName(),
      MT_MediaCampaign__c.MT_KRSID__c.getDescribe().getName(),
      MT_MediaCampaign__c.MT_MediaCampaignType_ref__c.getDescribe().getName()
    };

    MT_MediaCampaignSelector sel = new MT_MediaCampaignSelector();

    Test.startTest();
    List<sObject> records = sel.getRecordsByKrsIds(krsIds, fields);
    Test.stopTest();

    System.assertNotEquals(null, records, 'No records were returned');
    System.assertEquals(campaigns.size(), records.size(), 'An other number of records was returned than should be.');

    System.assertEquals(true, records instanceof List<MT_MediaCampaign__c>, 'Returned results are not of instance ' + MT_MediaCampaign__c.getSObjectType().getDescribe().getName());

    for (MT_MediaCampaign__c campaign : (List<MT_MediaCampaign__c>) records) {
      for (String field : fields) {
        System.assertNotEquals(null, campaign.get(field), 'Field ' + field + ' has not been selected!');
      }
      System.assertEquals(true, krsIds.contains(campaign.MT_KRSID__c), 'A campaign with an unknown KRS ID has been returned. KRS ID: ' + campaign.MT_KRSID__c);
      krsIds.remove(campaign.MT_KRSID__c);
    }

    System.assert(krsIds.isEmpty(), 'All KRS IDs should have been found and returned, but these are ' + krsIds.size() + ' missing!');
  }
}