src/objects/MT_MediaBroadcastImportControlData__c.object
<CustomObject>
    <description>Media Broadcast Import Control Data object will have a single record summarizing the total number of records and their value totals for each of the data load by external integrating system</description>
    <fields>
        <fullName>Import_Date_Unique__c</fullName>
        <description>To maintain a single record per day</description>
        <label>Import Date Unique</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MT_ImportDate__c</fullName>
        <label>Import Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_RecordCount__c</fullName>
        <label>Record Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MT_SumMB1__c</fullName>
        <label>Sum MB1</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_SumMB3__c</fullName>
        <label>Sum MB3</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_SumMN3__c</fullName>
        <label>Sum MN3</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Media Broadcast Import Control Data</label>
    <nameField>
        <displayFormat>DIM-{0000000000}</displayFormat>
        <label>Data Import Thread ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Broadcast Import Control Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_MediaBIControlData_TriggerHandlerTest.cls
/**
 * Test class for the Broadcast Import Data trigger handler.
 */
@IsTest
private class MT_MediaBIControlData_TriggerHandlerTest {
  @IsTest
  private static void testBeforeInsert() {
    MT_MediaBroadcastImportControlData__c rec = new MT_MediaBroadcastImportControlData__c(
      MT_ImportDate__c = System.today(),
      MT_RecordCount__c = 1,
      MT_SumMB1__c = 1,
      MT_SumMB3__c = 1,
      MT_SumMN3__c = 1
    );

    Test.startTest();
    insert rec;
    Test.stopTest();

    MT_MediaBroadcastImportControlData__c rec2 = [SELECT Import_Date_Unique__c
                                                    FROM MT_MediaBroadcastImportControlData__c
                                                   WHERE Id = :rec.Id];
    System.assertEquals(String.valueOf(rec.MT_ImportDate__c), rec2.Import_Date_Unique__c, 'Import date has not been copied into technical field for uniqueness check.');
  }

  @IsTest
  private static void testAfterInsert() {
    Integer noOfJobsBefore = [SELECT Id
                                FROM AsyncApexJob
                               WHERE JobType = 'BatchApex'
                                 AND Status IN ('Holding', 'Queued')
                                 AND ApexClass.NamespacePrefix = null
                                 AND ApexClass.Name = :MT_BroadcastImportDataValidator.class.getName()].size();

    MT_MediaBroadcastImportControlData__c rec = new MT_MediaBroadcastImportControlData__c(
      MT_ImportDate__c = System.today(),
      MT_RecordCount__c = 1,
      MT_SumMB1__c = 1,
      MT_SumMB3__c = 1,
      MT_SumMN3__c = 1
    );

    // startTest
    insert rec;
    // stopTest

    Integer noOfJobsAfter = [SELECT Id
                               FROM AsyncApexJob
                              WHERE JobType = 'BatchApex'
                                AND Status IN ('Holding', 'Queued')
                                AND ApexClass.NamespacePrefix = null
                                AND ApexClass.Name = :MT_BroadcastImportDataValidator.class.getName()].size();
    System.assertEquals(noOfJobsBefore + 1, noOfJobsAfter, 'Transformation batch has not been started.');
  }

}