src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <description>Planungsgrundlage für die Ausstrahlung eines Teils (oder des gesamten) BMV eines Restwerbeplatzvertrags. Enthält Informationen zur Ausstrahlung und Umsätzen, um die Planung und späteres Ranking zu ermöglichen.</description>
    <fields>
        <fullName>MT_Responsible_IM_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Der für diese Kampagne verantwortliche Benutzer von der IMA. Wird für Approval Prozesse und Benachrichtigungen im Flightplan verwendet.</description>
        <label>Internal Media Agency Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only users with the P7S1 Internal Agency role can be responsible internal media agents for a campaign.</errorMessage>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>P7S1_InternalAgency</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>MT_ResponsibleForMediaCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_Status__c</fullName>
        <description>Der aktuelle Status der Kampagne (Entwurf, Freigegeben, Abgeschlossen, Abgebrochen)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planning final</fullName>
                </value>
                <value>
                    <fullName>Campaign approved</fullName>
                </value>
                <value>
                    <fullName>Campaign changed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Approvals</fullName>
                </value>
                <value>
                    <fullName>Contract signed</fullName>
                    <isActive>false</isActive>
                    <label>Contract signed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_Sys_ApprovalSubmittedFromCampaign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Wird zur Steuerung der Approvalprozesse MT_OppApp_ChangeExternalApproval und MT_OppApp_ChangeInternalApproval genutzt. Es wird per Code in der Klasse MT_ApprovalProcessModule aktiviert, um die Einstiegskriterien für die Prozesse zu erfüllen, die sonst nicht greifen sollen. Die Klasse wird per Custom Button aufgerufen, der Button ist jedoch zur Zeit inaktiv, da die Freigabeprozesse für MT überarbeitet werden sollen.</description>
        <label>MT_Sys_ApprovalSubmittedFromCampaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_ApprovalState__c</fullName>
        <label>Genehmigungsstatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eingereicht</fullName>
                </value>
                <value>
                    <fullName>In Diskussion</fullName>
                </value>
                <value>
                    <fullName>Genehmigt</fullName>
                </value>
                <value>
                    <fullName>Abgelehnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_ApprovalProcessModule.cls
global class MT_ApprovalProcessModule {
  webservice static String startApprovalProcess(String strOppAppId, String strCampId) {
    MT_Constants constants = MT_Constants.getInstance();

    ID oppAppId = strOppAppId;
    ID campId = strCampId;

    P7S1_OpportunityApproval__c oppApp = (P7S1_OpportunityApproval__c) (new MT_OpportunityApprovalSelector()).getRecordsByIds(new Set<Id>{
      strOppAppId
    }, new Set<String>{
      'P7S1_ApprovalState__c', 'MT_Sys_ApprovalSubmittedFromCampaign__c'
    }).get(0);

    MT_MediaCampaign__c mc;

    Approval.ProcessSubmitRequest psr = new Approval.ProcessSubmitRequest();
    psr.setComments(constants.MediaCampaign_Approval_Comment);
    psr.setSubmitterId(UserInfo.getUserId());
    psr.setObjectId(oppAppId);

    if (oppApp.P7S1_ApprovalState__c == constants.OpportunityApproval_ApprovalStatus_Approved) {
      oppApp.MT_Sys_ApprovalSubmittedFromCampaign__c = true;
      update oppApp;

      mc = (MT_MediaCampaign__c) (new MT_MediaCampaignSelector()).getRecordsByIds(new Set<Id>{
        strCampId
      }, new Set<String>{
        'RecordType.DeveloperName', 'MT_Responsible_IM_Agent__c'
      }).get(0);

      if (mc.RecordType.DeveloperName == constants.MediaCampaign_RecordType_Internal) {
        if (mc.MT_Responsible_IM_Agent__c != null) {
          psr.setNextApproverIds(new List<Id>{
            mc.MT_Responsible_IM_Agent__c
          });

          psr.setProcessDefinitionNameOrId(constants.OpportunityApproval_ApprovalProcess_InternalCampaignChanged);
        }
      } else {
        psr.setProcessDefinitionNameOrId(constants.OpportunityApproval_ApprovalProcess_ExternalCampaignChanged);
      }

      if (String.isBlank(psr.getProcessDefinitionNameOrId())) {
        return MT_Labels.getInstance().MSG_ApprovalModule_EntryFailure;
      }
    }

    Approval.ProcessResult result;
    try {
      result = Approval.process(psr);
    } catch (DmlException e) {
      return MT_Labels.getInstance().MSG_ApprovalModule_Failure.replace('@error', e.getMessage());
    }

    if (result.isSuccess()) {
      if (mc != null) {
        mc.MT_Status__c = constants.MediaCampaign_Status_InApprovals;
        update mc;
      }

      if (oppApp.MT_Sys_ApprovalSubmittedFromCampaign__c) {
        oppApp.MT_Sys_ApprovalSubmittedFromCampaign__c = false;
        update oppApp;
      }

      return MT_Labels.getInstance().MSG_ApprovalModule_Success;
    } else {
      String errors = '';

      for (Database.Error error : result.getErrors()) {
        if (!String.isBlank(errors)) {
          errors += '; ';
        }

        errors += error.getMessage();
      }

      return MT_Labels.getInstance().MSG_ApprovalModule_Failure.replace('@error', errors);
    }
  }
}