src/objects/P7S1_Asset__c.object
<CustomObject>
    <description>Wird benutzt, um die Marken (Assets) der Units zu pflegen.</description>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Die Unit, zu dem das Asset gehört.</description>
        <label>Unit</label>
        <referenceTo>P7S1_Unit__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Unit__c.object
<CustomObject>
    <description>Die Business Unit, die Kampagnen mit externen Partnern oder interne Kampagnen durchführt.</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_Assets.cls
/************************************************************************************************************
Name:  		MT_Assets
======================================================
Purpose: 	Domain class for P7S1_Asset__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
08.03.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/
public with sharing class MT_Assets {
  private List<P7S1_Asset__c> scope;

  public MT_Assets(List<P7S1_Asset__c> scope) {
    this.scope = scope;
  }

  public static P7S1_Asset__c create(P7S1_Unit__c unit, String name) {
    return new P7S1_Asset__c(
      P7S1_Unit__c = unit.Id,
      Name = name);
  }

  public class MT_AssetsException extends Exception {
  }
}