src/objects/P7S1_Unit__c.object
<CustomObject>
    <description>Die Business Unit, die Kampagnen mit externen Partnern oder interne Kampagnen durchführt.</description>
    <fields>
        <fullName>P7S1_Segment__c</fullName>
        <description>Das Segment, zu dem die Unit gehört. Wird im Forecasting zur Strukturierung genutzt.</description>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D&amp;A</fullName>
                    <default>true</default>
                    <label>D&amp;A</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_Units.cls
/************************************************************************************************************
Name:  		MT_Units
======================================================
Purpose: 	Domain class for P7S1_Unit__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
08.03.2017	Falco Aulitzky	            Initial architecture & development
*************************************************************************************************************/

public with sharing class MT_Units {
  private List<P7S1_Unit__c> scope;

  public MT_Units(List<P7S1_Unit__c> scope) {
    this.scope = scope;
  }

  public static P7S1_Unit__c create(String segment, String name) {
    return new P7S1_Unit__c(
      P7S1_Segment__c = segment,
      Name = name);
  }

  public class MT_UnitsException extends Exception {
  }
}