src/objects/P7S1_Asset__c.object
<CustomObject>
    <description>Wird benutzt, um die Marken (Assets) der Units zu pflegen.</description>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Die Unit, zu dem das Asset gehört.</description>
        <label>Unit</label>
        <referenceTo>P7S1_Unit__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Unit__c.object
<CustomObject>
    <description>Die Business Unit, die Kampagnen mit externen Partnern oder interne Kampagnen durchführt.</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_UnitService.cls
/************************************************************************************************************
Name:  		MT_UnitService
======================================================
Purpose: 	Service class for P7S1_Unit__c object
======================================================
History
-------
Date		AUTHOR						DETAIL
08.03.2017	Falco Aulitzky              Initial architecture & development
*************************************************************************************************************/

global with sharing class MT_UnitService {
  global static List<P7S1_Unit__c> getUnitsByIds(Set<Id> recordIds) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_UnitSelector().getRecordsByIds(
      recordIds,
      MT_FieldSet.getFields(SObjectType.P7S1_Unit__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<P7S1_Unit__c> getUnitsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_UnitSelector().getRecordsByIds(
      recordIds,
      fields
    );
  }

  global static List<P7S1_Unit__c> getUnitsWithAssetsByIds(Set<Id> recordIds) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_UnitSelector().getRecordsWithAssetsByIds(
      recordIds,
      MT_FieldSet.getFields(SObjectType.P7S1_Unit__c.FieldSets.MT_ContextFields),
      MT_FieldSet.getFields(SObjectType.P7S1_Asset__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<P7S1_Unit__c> getUnitsWithAssetsByIds(Set<Id> recordIds, Set<String> unitFields, Set<String> assetFields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_UnitSelector().getRecordsWithAssetsByIds(
      recordIds,
      unitFields,
      assetFields
    );
  }

  global static List<P7S1_Unit__c> getUnitsBySegments(Set<String> segments) {
    if (segments.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_UnitSelector().getRecordsBySegments(
      segments,
      MT_FieldSet.getFields(SObjectType.P7S1_Unit__c.FieldSets.MT_ContextFields)
    );
  }

  global static List<P7S1_Unit__c> getUnitsBySegments(Set<String> segments, Set<String> fields) {
    if (segments.isEmpty()) {
      return new List<SObject>();
    }

    return new MT_UnitSelector().getRecordsBySegments(
      segments,
      fields
    );
  }
}